#define DEFAULT_XKB_LAYOUT "us"
#define DEFAULT_XKB_MODEL "pc105"
#define DEFAULT_XKB_RULES "evdev"
#define DFLT_XKB_CONFIG_ROOT "/share/xkb"
#define HAVE_EACCESS 1
#define HAVE_EUIDACCESS 1
#define HAVE_MKOSTEMP 1
#define HAVE_MMAP 1
#define HAVE_POSIX_FALLOCATE 1
#define HAVE___BUILTIN_EXPECT 1
#define XLOCALEDIR "/share/xlocale"
#define _GNU_SOURCE 1
