/* #undef AARCH64 */
/* #undef AC_APPLE_UNIVERSAL_BUILD */
/* #undef ALPHA */
/* #undef ARC */
/* #undef ARM */
#define ASM_SA_RESTORER 0x04000000
#define ASM_SIGRTMIN 32
/* #undef AVR32 */
/* #undef BFIN */
#define COPYRIGHT_YEAR "2018"
#define ENABLE_ARM_OABI 0
#define HAVE_ACCEPT4 1
/* #undef HAVE_ASM_CACHECTL_H */
/* #undef HAVE_ASM_GUARDED_STORAGE_H */
/* #undef HAVE_ASM_SIGCONTEXT_H */
/* #undef HAVE_ASM_SYSMIPS_H */
/* #undef HAVE_BE64TOH */
#define HAVE_BLKGETSIZE64 1
/* #undef HAVE_BLUETOOTH_BLUETOOTH_H */
#define HAVE_DECL_BTRFS_COMPRESS_LZO 0
#define HAVE_DECL_BTRFS_COMPRESS_NONE 0
#define HAVE_DECL_BTRFS_COMPRESS_ZLIB 0
#define HAVE_DECL_CTL_ARLAN 1
#define HAVE_DECL_CTL_FRV 1
#define HAVE_DECL_CTL_PM 1
#define HAVE_DECL_CTL_PROC 1
#define HAVE_DECL_CTL_S390DBF 1
#define HAVE_DECL_CTL_SUNRPC 1
#define HAVE_DECL_KERN_ACPI_VIDEO_FLAGS 1
#define HAVE_DECL_KERN_BOOTLOADER_TYPE 1
#define HAVE_DECL_KERN_COMPAT_LOG 1
#define HAVE_DECL_KERN_HZ_TIMER 1
#define HAVE_DECL_KERN_IA64_UNALIGNED 1
#define HAVE_DECL_KERN_MAX_LOCK_DEPTH 1
#define HAVE_DECL_KERN_NGROUPS_MAX 1
#define HAVE_DECL_KERN_NMI_WATCHDOG 1
#define HAVE_DECL_KERN_PANIC_ON_NMI 1
#define HAVE_DECL_KERN_PRINTK_RATELIMIT 1
#define HAVE_DECL_KERN_PRINTK_RATELIMIT_BURST 1
#define HAVE_DECL_KERN_PTY 1
#define HAVE_DECL_KERN_RANDOMIZE 1
#define HAVE_DECL_KERN_SETUID_DUMPABLE 1
#define HAVE_DECL_KERN_SPARC_SCONS_PWROFF 1
#define HAVE_DECL_KERN_SPIN_RETRY 1
#define HAVE_DECL_KERN_UNKNOWN_NMI_PANIC 1
#define HAVE_DECL_LO_FLAGS_AUTOCLEAR 1
#define HAVE_DECL_LO_FLAGS_DIRECT_IO 1
#define HAVE_DECL_LO_FLAGS_PARTSCAN 1
#define HAVE_DECL_LO_FLAGS_READ_ONLY 1
#define HAVE_DECL_LO_FLAGS_USE_AOPS 0
#define HAVE_DECL_NET_CIPSOV4_CACHE_BUCKET_SIZE 1
#define HAVE_DECL_NET_CIPSOV4_CACHE_ENABLE 1
#define HAVE_DECL_NET_CIPSOV4_RBM_OPTFMT 1
#define HAVE_DECL_NET_CIPSOV4_RBM_STRICTVALID 1
#define HAVE_DECL_NET_CORE_AEVENT_ETIME 1
#define HAVE_DECL_NET_CORE_AEVENT_RSEQTH 1
#define HAVE_DECL_NET_CORE_BUDGET 1
#define HAVE_DECL_NET_CORE_DESTROY_DELAY 0
#define HAVE_DECL_NET_CORE_WARNINGS 1
#define HAVE_DECL_NET_DCCP 1
#define HAVE_DECL_NET_IPV4_CONF_ARP_ACCEPT 1
#define HAVE_DECL_NET_IPV4_CONF_ARP_ANNOUNCE 1
#define HAVE_DECL_NET_IPV4_CONF_ARP_IGNORE 1
#define HAVE_DECL_NET_IPV4_CONF_ARP_NOTIFY 1
#define HAVE_DECL_NET_IPV4_CONF_FORCE_IGMP_VERSION 1
#define HAVE_DECL_NET_IPV4_CONF_PROMOTE_SECONDARIES 1
#define HAVE_DECL_NET_IPV4_ICMP_ERRORS_USE_INBOUND_IFADDR 1
#define HAVE_DECL_NET_IPV4_IGMP_MAX_MSF 1
#define HAVE_DECL_NET_IPV4_IPFRAG_MAX_DIST 1
#define HAVE_DECL_NET_IPV4_ROUTE_GC_MIN_INTERVAL_MS 1
#define HAVE_DECL_NET_IPV4_TCP_WORKAROUND_SIGNED_WINDOWS 1
#define HAVE_DECL_NET_IPV6_MLD_MAX_MSF 1
#define HAVE_DECL_NET_IPV6_ROUTE_GC_MIN_INTERVAL_MS 1
#define HAVE_DECL_NET_IRDA 1
#define HAVE_DECL_NET_LLC 1
#define HAVE_DECL_NET_NETFILTER 1
#define HAVE_DECL_NET_TCP_ABC 1
#define HAVE_DECL_NET_TCP_ALLOWED_CONG_CONTROL 1
#define HAVE_DECL_NET_TCP_AVAIL_CONG_CONTROL 1
#define HAVE_DECL_NET_TCP_BASE_MSS 1
#define HAVE_DECL_NET_TCP_BIC_BETA 1
#define HAVE_DECL_NET_TCP_CONG_CONTROL 1
#define HAVE_DECL_NET_TCP_DEFAULT_WIN_SCALE 1
#define HAVE_DECL_NET_TCP_DMA_COPYBREAK 1
#define HAVE_DECL_NET_TCP_FRTO_RESPONSE 1
#define HAVE_DECL_NET_TCP_MAX_SSTHRESH 1
#define HAVE_DECL_NET_TCP_MODERATE_RCVBUF 1
#define HAVE_DECL_NET_TCP_MTU_PROBING 1
#define HAVE_DECL_NET_TCP_NO_METRICS_SAVE 1
#define HAVE_DECL_NET_TCP_SLOW_START_AFTER_IDLE 1
#define HAVE_DECL_NET_TCP_TSO_WIN_DIVISOR 1
#define HAVE_DECL_PTRACE_PEEKUSER 1
#define HAVE_DECL_PTRACE_POKEUSER 1
#define HAVE_DECL_P_ALL 1
#define HAVE_DECL_P_CID 0
#define HAVE_DECL_P_GID 0
#define HAVE_DECL_P_LWPID 0
#define HAVE_DECL_P_PGID 1
#define HAVE_DECL_P_PID 1
#define HAVE_DECL_P_PPID 0
#define HAVE_DECL_P_SID 0
#define HAVE_DECL_P_UID 0
#define HAVE_DECL_SYS_ERRLIST 0
#define HAVE_DECL_V4L2_BUF_TYPE_SDR_CAPTURE 1
#define HAVE_DECL_V4L2_BUF_TYPE_SDR_OUTPUT 1
#define HAVE_DECL_V4L2_BUF_TYPE_SLICED_VBI_CAPTURE 1
#define HAVE_DECL_V4L2_BUF_TYPE_SLICED_VBI_OUTPUT 1
#define HAVE_DECL_V4L2_BUF_TYPE_VBI_CAPTURE 1
#define HAVE_DECL_V4L2_BUF_TYPE_VBI_OUTPUT 1
#define HAVE_DECL_V4L2_BUF_TYPE_VIDEO_CAPTURE 1
#define HAVE_DECL_V4L2_BUF_TYPE_VIDEO_CAPTURE_MPLANE 1
#define HAVE_DECL_V4L2_BUF_TYPE_VIDEO_OUTPUT 1
#define HAVE_DECL_V4L2_BUF_TYPE_VIDEO_OUTPUT_MPLANE 1
#define HAVE_DECL_V4L2_BUF_TYPE_VIDEO_OUTPUT_OVERLAY 1
#define HAVE_DECL_V4L2_BUF_TYPE_VIDEO_OVERLAY 1
#define HAVE_DECL_V4L2_COLORSPACE_470_SYSTEM_BG 1
#define HAVE_DECL_V4L2_COLORSPACE_470_SYSTEM_M 1
#define HAVE_DECL_V4L2_COLORSPACE_BT878 1
#define HAVE_DECL_V4L2_COLORSPACE_JPEG 1
#define HAVE_DECL_V4L2_COLORSPACE_REC709 1
#define HAVE_DECL_V4L2_COLORSPACE_SMPTE170M 1
#define HAVE_DECL_V4L2_COLORSPACE_SMPTE240M 1
#define HAVE_DECL_V4L2_COLORSPACE_SRGB 1
#define HAVE_DECL_V4L2_CTRL_TYPE_BITMASK 1
#define HAVE_DECL_V4L2_CTRL_TYPE_BOOLEAN 1
#define HAVE_DECL_V4L2_CTRL_TYPE_BUTTON 1
#define HAVE_DECL_V4L2_CTRL_TYPE_CTRL_CLASS 1
#define HAVE_DECL_V4L2_CTRL_TYPE_INTEGER 1
#define HAVE_DECL_V4L2_CTRL_TYPE_INTEGER64 1
#define HAVE_DECL_V4L2_CTRL_TYPE_INTEGER_MENU 1
#define HAVE_DECL_V4L2_CTRL_TYPE_MENU 1
#define HAVE_DECL_V4L2_CTRL_TYPE_STRING 1
#define HAVE_DECL_V4L2_FIELD_ALTERNATE 1
#define HAVE_DECL_V4L2_FIELD_ANY 1
#define HAVE_DECL_V4L2_FIELD_BOTTOM 1
#define HAVE_DECL_V4L2_FIELD_INTERLACED 1
#define HAVE_DECL_V4L2_FIELD_INTERLACED_BT 1
#define HAVE_DECL_V4L2_FIELD_INTERLACED_TB 1
#define HAVE_DECL_V4L2_FIELD_NONE 1
#define HAVE_DECL_V4L2_FIELD_SEQ_BT 1
#define HAVE_DECL_V4L2_FIELD_SEQ_TB 1
#define HAVE_DECL_V4L2_FIELD_TOP 1
#define HAVE_DECL_V4L2_FRMIVAL_TYPE_CONTINUOUS 1
#define HAVE_DECL_V4L2_FRMIVAL_TYPE_DISCRETE 1
#define HAVE_DECL_V4L2_FRMIVAL_TYPE_STEPWISE 1
#define HAVE_DECL_V4L2_FRMSIZE_TYPE_CONTINUOUS 1
#define HAVE_DECL_V4L2_FRMSIZE_TYPE_DISCRETE 1
#define HAVE_DECL_V4L2_FRMSIZE_TYPE_STEPWISE 1
#define HAVE_DECL_V4L2_MEMORY_DMABUF 1
#define HAVE_DECL_V4L2_MEMORY_MMAP 1
#define HAVE_DECL_V4L2_MEMORY_OVERLAY 1
#define HAVE_DECL_V4L2_MEMORY_USERPTR 1
#define HAVE_DECL_V4L2_PRIORITY_BACKGROUND 1
#define HAVE_DECL_V4L2_PRIORITY_INTERACTIVE 1
#define HAVE_DECL_V4L2_PRIORITY_RECORD 1
#define HAVE_DECL_V4L2_PRIORITY_UNSET 1
#define HAVE_DECL_V4L2_TUNER_ANALOG_TV 1
#define HAVE_DECL_V4L2_TUNER_DIGITAL_TV 1
#define HAVE_DECL_V4L2_TUNER_RADIO 1
#define HAVE_DECL_VM_BLOCK_DUMP 1
#define HAVE_DECL_VM_HUGETLB_GROUP 1
#define HAVE_DECL_VM_LAPTOP_MODE 1
#define HAVE_DECL_VM_LEGACY_VA_LAYOUT 1
#define HAVE_DECL_VM_MAX_MAP_COUNT 1
#define HAVE_DECL_VM_SWAP_TOKEN_TIMEOUT 1
#define HAVE_DECL_VM_VFS_CACHE_PRESSURE 1
/* #undef HAVE_DEMANGLE_H */
#define HAVE_DLADDR 1
#define HAVE_ELF_H 1
#define HAVE_FALLOCATE 1
#define HAVE_FANOTIFY_MARK 1
#define HAVE_FOPEN64 1
#define HAVE_FORK 1
#define HAVE_FPUTS_UNLOCKED 1
#define HAVE_FSTATAT 1
#define HAVE_FTRUNCATE 1
#define HAVE_FUTIMENS 1
/* #undef HAVE_GNU_STUBS */
/* #undef HAVE_GNU_STUBS_32_H */
/* #undef HAVE_GNU_STUBS_X32_H */
#define HAVE_ICONV_H 1
#define HAVE_ICONV_OPEN 1
#define HAVE_IF_INDEXTONAME 1
#define HAVE_INTTYPES_H 1
/* #undef HAVE_LIBIBERTY_DEMANGLE_H */
/* #undef HAVE_LIBUNWIND_PTRACE_H */
#define HAVE_LINUX_BPF_H 1
#define HAVE_LINUX_BSG_H 1
#define HAVE_LINUX_BTRFS_H 1
/* #undef HAVE_LINUX_CRYPTOUSER_H */
#define HAVE_LINUX_DM_IOCTL_H 1
#define HAVE_LINUX_DQBLK_XFS_H 1
#define HAVE_LINUX_FALLOC_H 1
#define HAVE_LINUX_FIB_RULES_H 1
#define HAVE_LINUX_FIEMAP_H 1
#define HAVE_LINUX_GENETLINK_H 1
#define HAVE_LINUX_HIDDEV_H 1
#define HAVE_LINUX_IF_ADDR_H 1
#define HAVE_LINUX_IF_LINK_H 1
#define HAVE_LINUX_INPUT_H 1
#define HAVE_LINUX_IPC_H 1
#define HAVE_LINUX_IP_VS_H 1
#define HAVE_LINUX_KCMP_H 1
#define HAVE_LINUX_KVM_H 1
#define HAVE_LINUX_MEMFD_H 1
#define HAVE_LINUX_MMTIMER_H 1
#define HAVE_LINUX_MQUEUE_H 1
#define HAVE_LINUX_MSG_H 1
#define HAVE_LINUX_NEIGHBOUR_H 1
#define HAVE_LINUX_NETFILTER_ARP_ARP_TABLES_H 1
#define HAVE_LINUX_NETFILTER_BRIDGE_EBTABLES_H 1
#define HAVE_LINUX_NETFILTER_IPSET_IP_SET_H 1
#define HAVE_LINUX_NETFILTER_IPV4_IP_TABLES_H 1
#define HAVE_LINUX_NETFILTER_IPV6_IP6_TABLES_H 1
#define HAVE_LINUX_NETFILTER_NFNETLINK_ACCT_H 1
#define HAVE_LINUX_NETFILTER_NFNETLINK_CONNTRACK_H 1
#define HAVE_LINUX_NETFILTER_NFNETLINK_CTHELPER_H 1
#define HAVE_LINUX_NETFILTER_NFNETLINK_CTTIMEOUT_H 1
#define HAVE_LINUX_NETFILTER_NFNETLINK_H 1
#define HAVE_LINUX_NETFILTER_NFNETLINK_LOG_H 1
#define HAVE_LINUX_NETFILTER_NFNETLINK_QUEUE_H 1
#define HAVE_LINUX_NETFILTER_NF_TABLES_COMPAT_H 1
#define HAVE_LINUX_NETFILTER_NF_TABLES_H 1
#define HAVE_LINUX_NETFILTER_XT_OSF_H 1
/* #undef HAVE_LINUX_NSFS_H */
#define HAVE_LINUX_PERF_EVENT_H 1
#define HAVE_LINUX_QUOTA_H 1
#define HAVE_LINUX_SECCOMP_H 1
#define HAVE_LINUX_SECUREBITS_H 1
#define HAVE_LINUX_SEM_H 1
#define HAVE_LINUX_SHM_H 1
#define HAVE_LINUX_USERFAULTFD_H 1
#define HAVE_LINUX_UTSNAME_H 1
/* #undef HAVE_M32_MPERS */
/* #undef HAVE_M32_STRUCT_STAT */
/* #undef HAVE_M32_STRUCT_STAT64 */
/* #undef HAVE_M32_STRUCT_STAT64_ST_MTIME_NSEC */
/* #undef HAVE_M32_STRUCT_STAT_ST_MTIME_NSEC */
#define HAVE_MEMORY_H 1
#define HAVE_MQUEUE_H 1
/* #undef HAVE_MX32_MPERS */
/* #undef HAVE_MX32_STRUCT_STAT */
/* #undef HAVE_MX32_STRUCT_STAT64 */
/* #undef HAVE_MX32_STRUCT_STAT64_ST_MTIME_NSEC */
/* #undef HAVE_MX32_STRUCT_STAT_ST_MTIME_NSEC */
/* #undef HAVE_NETINET_SCTP_H */
#define HAVE_NETINET_TCP_H 1
#define HAVE_NETINET_UDP_H 1
/* #undef HAVE_NETIPX_IPX_H */
#define HAVE_OPEN64 1
#define HAVE_PATHS_H 1
#define HAVE_PRCTL 1
#define HAVE_PREADV 1
#define HAVE_PROCESS_VM_READV 1
#define HAVE_PROGRAM_INVOCATION_NAME 1
#define HAVE_PWRITEV 1
#define HAVE_READAHEAD 1
#define HAVE_SCSI_SG_H 1
#define HAVE_SIGINFO_T_SI_OVERRUN 1
#define HAVE_SIGINFO_T_SI_SYSCALL 1
#define HAVE_SIGINFO_T_SI_TIMERID 1
#define HAVE_SIGNALFD 1
#define HAVE_SIG_ATOMIC_T 1
#define HAVE_STDINT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STPCPY 1
#define HAVE_STRERROR 1
#define HAVE_STRINGS_H 1
#define HAVE_STRING_H 1
#define HAVE_STRNDUP 1
#define HAVE_STROPTS_H 1
#define HAVE_STRSIGNAL 1
#define HAVE_STRUCT_BLK_USER_TRACE_SETUP 1
#define HAVE_STRUCT_BR_MDB_ENTRY 1
/* #undef HAVE_STRUCT_BR_MDB_ENTRY_FLAGS */
#define HAVE_STRUCT_BR_MDB_ENTRY_VID 1
#define HAVE_STRUCT_BR_PORT_MSG 1
/* #undef HAVE_STRUCT_BTRFS_IOCTL_DEFRAG_RANGE_ARGS_START */
#define HAVE_STRUCT_BTRFS_IOCTL_FEATURE_FLAGS_COMPAT_FLAGS 1
#define HAVE_STRUCT_BTRFS_IOCTL_FS_INFO_ARGS_NODESIZE 1
#define HAVE_STRUCT_BTRFS_IOCTL_SEARCH_ARGS_V2_BUF_SIZE 1
/* #undef HAVE_STRUCT_CRYPTO_REPORT_AEAD */
/* #undef HAVE_STRUCT_CRYPTO_REPORT_BLKCIPHER */
/* #undef HAVE_STRUCT_CRYPTO_REPORT_CIPHER */
/* #undef HAVE_STRUCT_CRYPTO_REPORT_HASH */
/* #undef HAVE_STRUCT_CRYPTO_REPORT_RNG */
#define HAVE_STRUCT_DCBMSG 1
/* #undef HAVE_STRUCT_FIB_RULE_UID_RANGE */
#define HAVE_STRUCT_FLOCK 1
#define HAVE_STRUCT_FLOCK64 1
#define HAVE_STRUCT_GNET_STATS_BASIC 1
#define HAVE_STRUCT_GNET_STATS_QUEUE 1
#define HAVE_STRUCT_GNET_STATS_RATE_EST 1
#define HAVE_STRUCT_GNET_STATS_RATE_EST64 1
/* #undef HAVE_STRUCT_IA64_FPREG */
#define HAVE_STRUCT_IFADDRLBLMSG 1
#define HAVE_STRUCT_IFLA_BRIDGE_ID 1
#define HAVE_STRUCT_IFLA_PORT_VSI 1
#define HAVE_STRUCT_INPUT_ABSINFO_RESOLUTION 1
/* #undef HAVE_STRUCT_KCMP_EPOLL_SLOT */
/* #undef HAVE_STRUCT_KEYCTL_KDF_PARAMS */
#define HAVE_STRUCT_KVM_REGS 1
#define HAVE_STRUCT_KVM_SREGS 1
#define HAVE_STRUCT_KVM_USERSPACE_MEMORY_REGION 1
#define HAVE_STRUCT_MMSGHDR 1
#define HAVE_STRUCT_MTD_WRITE_REQ 1
#define HAVE_STRUCT_NDT_CONFIG 1
#define HAVE_STRUCT_NDT_STATS 1
#define HAVE_STRUCT_NDT_STATS_NDTS_TABLE_FULLS 1
#define HAVE_STRUCT_NETCONFMSG 1
#define HAVE_STRUCT_PERF_EVENT_ATTR_AUX_WATERMARK 1
#define HAVE_STRUCT_PERF_EVENT_ATTR_BP_TYPE 1
#define HAVE_STRUCT_PERF_EVENT_ATTR_BRANCH_SAMPLE_TYPE 1
#define HAVE_STRUCT_PERF_EVENT_ATTR_COMM_EXEC 1
#define HAVE_STRUCT_PERF_EVENT_ATTR_CONFIG1 1
#define HAVE_STRUCT_PERF_EVENT_ATTR_CONFIG2 1
#define HAVE_STRUCT_PERF_EVENT_ATTR_CONTEXT_SWITCH 1
#define HAVE_STRUCT_PERF_EVENT_ATTR_EXCLUDE_CALLCHAIN_KERNEL 1
#define HAVE_STRUCT_PERF_EVENT_ATTR_EXCLUDE_CALLCHAIN_USER 1
#define HAVE_STRUCT_PERF_EVENT_ATTR_EXCLUDE_GUEST 1
#define HAVE_STRUCT_PERF_EVENT_ATTR_EXCLUDE_HOST 1
#define HAVE_STRUCT_PERF_EVENT_ATTR_MMAP2 1
#define HAVE_STRUCT_PERF_EVENT_ATTR_MMAP_DATA 1
/* #undef HAVE_STRUCT_PERF_EVENT_ATTR_NAMESPACES */
#define HAVE_STRUCT_PERF_EVENT_ATTR_PRECISE_IP 1
#define HAVE_STRUCT_PERF_EVENT_ATTR_SAMPLE_ID_ALL 1
/* #undef HAVE_STRUCT_PERF_EVENT_ATTR_SAMPLE_MAX_STACK */
#define HAVE_STRUCT_PERF_EVENT_ATTR_SAMPLE_REGS_INTR 1
#define HAVE_STRUCT_PERF_EVENT_ATTR_SAMPLE_REGS_USER 1
#define HAVE_STRUCT_PERF_EVENT_ATTR_SAMPLE_STACK_USER 1
#define HAVE_STRUCT_PERF_EVENT_ATTR_USE_CLOCKID 1
/* #undef HAVE_STRUCT_PERF_EVENT_ATTR_WRITE_BACKWARD */
#define HAVE_STRUCT_PTP_SYS_OFFSET 1
#define HAVE_STRUCT_PTRACE_PEEKSIGINFO_ARGS 1
/* #undef HAVE_STRUCT_PT_ALL_USER_REGS */
#define HAVE_STRUCT_RTA_MFC_STATS 1
#define HAVE_STRUCT_RTNL_LINK_STATS64 1
/* #undef HAVE_STRUCT_RTNL_LINK_STATS64_RX_NOHANDLER */
/* #undef HAVE_STRUCT_RTNL_LINK_STATS_RX_NOHANDLER */
#define HAVE_STRUCT_RTVIA 1
#define HAVE_STRUCT_SIGCONTEXT 1
/* #undef HAVE_STRUCT_STAT64 */
/* #undef HAVE_STRUCT_STAT64_ST_MTIME_NSEC */
#define HAVE_STRUCT_STATFS 1
#define HAVE_STRUCT_STATFS64 1
#define HAVE_STRUCT_STATFS64_F_FLAGS 1
#define HAVE_STRUCT_STATFS64_F_FRSIZE 1
#define HAVE_STRUCT_STATFS64_F_FSID_VAL 1
/* #undef HAVE_STRUCT_STATFS64_F_FSID___VAL */
#define HAVE_STRUCT_STATFS_F_FLAGS 1
#define HAVE_STRUCT_STATFS_F_FRSIZE 1
#define HAVE_STRUCT_STATFS_F_FSID_VAL 1
/* #undef HAVE_STRUCT_STATFS_F_FSID___VAL */
#define HAVE_STRUCT_STAT_ST_MTIME_NSEC 1
#define HAVE_STRUCT_TC_SIZESPEC 1
#define HAVE_STRUCT_TIMEX_TAI 1
#define HAVE_STRUCT_UBI_ATTACH_REQ_MAX_BEB_PER1024 1
#define HAVE_STRUCT_USER_DESC 1
#define HAVE_STRUCT_USER_DESC_LM 1
#define HAVE_STRUCT_UTSNAME_DOMAINNAME 1
#define HAVE_STRUCT_V4L2_SDR_FORMAT_BUFFERSIZE 1
#define HAVE_STRUCT_V4L2_WINDOW_GLOBAL_ALPHA 1
/* #undef HAVE_STRUCT___KERNEL_FLOCK */
/* #undef HAVE_STRUCT___KERNEL_FLOCK64 */
#define HAVE_STRUCT___OLD_KERNEL_STAT 1
#define HAVE_SYNC_FILE_RANGE 1
/* #undef HAVE_SYS_CONF_H */
#define HAVE_SYS_EVENTFD_H 1
#define HAVE_SYS_FANOTIFY_H 1
#define HAVE_SYS_IPC_H 1
#define HAVE_SYS_MSG_H 1
#define HAVE_SYS_QUOTA_H 1
#define HAVE_SYS_REG_H 1
#define HAVE_SYS_SEM_H 1
#define HAVE_SYS_SHM_H 1
#define HAVE_SYS_SIGNALFD_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_XATTR_H 1
#define HAVE_TYPEOF 1
/* #undef HAVE_UNION_BPF_ATTR_ATTACH_FLAGS */
#define HAVE_UNION_BPF_ATTR_BPF_FD 1
#define HAVE_UNION_BPF_ATTR_FLAGS 1
/* #undef HAVE_UNION_BPF_ATTR_INFO_INFO */
/* #undef HAVE_UNION_BPF_ATTR_NEXT_ID */
/* #undef HAVE_UNION_BPF_ATTR_NUMA_NODE */
/* #undef HAVE_UNION_BPF_ATTR_PROG_FLAGS */
/* #undef HAVE_UNION_BPF_ATTR_TEST_DURATION */
#define HAVE_UNISTD_H 1
/* #undef HAVE_USTAT_H */
#define HAVE_UTIMENSAT 1
#define HAVE___BUILTIN_POPCOUNT 1
#define HAVE___KERNEL_LONG_T 1
#define HAVE___KERNEL_ULONG_T 1
/* #undef HPPA */
/* #undef I386 */
/* #undef IA64 */
/* #undef LINUX_MIPSN32 */
/* #undef LINUX_MIPSN64 */
/* #undef LINUX_MIPSO32 */
/* #undef M32_SIZEOF_KERNEL_LONG_T */
/* #undef M32_SIZEOF_LONG */
/* #undef M68K */
#define MANPAGE_DATE "2018-02-11"
/* #undef METAG */
/* #undef MICROBLAZE */
/* #undef MIPS */
/* #undef MX32_SIZEOF_KERNEL_LONG_T */
/* #undef MX32_SIZEOF_LONG */
/* #undef NIOS2 */
/* #undef OR1K */
#define PACKAGE "strace"
#define PACKAGE_BUGREPORT "strace-devel@lists.sourceforge.net"
#define PACKAGE_NAME "strace"
#define PACKAGE_STRING "strace 4.21"
#define PACKAGE_TARNAME "strace"
#define PACKAGE_URL "https://strace.io"
#define PACKAGE_VERSION "4.21"
/* #undef POWERPC */
/* #undef POWERPC64 */
/* #undef RISCV */
/* #undef S390 */
/* #undef S390X */
/* #undef SH */
/* #undef SH64 */
#define SIZEOF_KERNEL_LONG_T 8
#define SIZEOF_LONG 8
#define SIZEOF_LONG_LONG 8
#define SIZEOF_OFF_T 8
#define SIZEOF_STRUCT_I64_I32 16
/* #undef SPARC */
/* #undef SPARC64 */
#define STDC_HEADERS 1
/* #undef TILE */
/* #undef USE_DEMANGLE */
/* #undef USE_LIBUNWIND */
#ifndef _ALL_SOURCE
# define _ALL_SOURCE 1
#endif
#ifndef _GNU_SOURCE
# define _GNU_SOURCE 1
#endif
#ifndef _POSIX_PTHREAD_SEMANTICS
# define _POSIX_PTHREAD_SEMANTICS 1
#endif
#ifndef _TANDEM_SOURCE
# define _TANDEM_SOURCE 1
#endif
#ifndef __EXTENSIONS__
# define __EXTENSIONS__ 1
#endif
#define VERSION "4.21"
#if defined AC_APPLE_UNIVERSAL_BUILD
# if defined __BIG_ENDIAN__
#  define WORDS_BIGENDIAN 1
# endif
#else
# ifndef WORDS_BIGENDIAN
/* #  undef WORDS_BIGENDIAN */
# endif
#endif
/* #undef X32 */
#define X86_64 1
/* #undef XTENSA */
/* #undef _MINIX */
/* #undef _POSIX_1_SOURCE */
/* #undef _POSIX_SOURCE */
/* #undef gid_t */
/* #undef typeof */
/* #undef uid_t */
