/* #undef AARCH64 */
/* #undef AC_APPLE_UNIVERSAL_BUILD */
/* #undef ALPHA */
/* #undef ARC */
/* #undef ARM */
#define ASM_SA_RESTORER 0x04000000
#define ASM_SIGRTMIN 32
/* #undef AVR32 */
/* #undef BFIN */
#define COPYRIGHT_YEAR "2023"
/* #undef CSKY */
#define ENABLE_ARM_OABI 0
/* #undef ENABLE_SECONTEXT */
/* #undef ENABLE_STACKTRACE */
#define HAVE_ACCEPT4 1
/* #undef HAVE_ASM_CACHECTL_H */
/* #undef HAVE_ASM_GUARDED_STORAGE_H */
/* #undef HAVE_ASM_SIGCONTEXT_H */
/* #undef HAVE_ASM_SYSMIPS_H */
/* #undef HAVE_BE64TOH */
/* #undef HAVE_BLUETOOTH_BLUETOOTH_H */
#define HAVE_DECL_IEEE802154_ADDR_LONG 0
#define HAVE_DECL_IEEE802154_ADDR_NONE 0
#define HAVE_DECL_IEEE802154_ADDR_SHORT 0
#define HAVE_DECL_LO_FLAGS_AUTOCLEAR 1
#define HAVE_DECL_LO_FLAGS_DIRECT_IO 1
#define HAVE_DECL_LO_FLAGS_PARTSCAN 1
#define HAVE_DECL_LO_FLAGS_READ_ONLY 1
#define HAVE_DECL_LO_FLAGS_USE_AOPS 0
#define HAVE_DECL_NFEA_ACTIVITY_NOTIFY 0
#define HAVE_DECL_NFEA_DONT_REFRESH 0
#define HAVE_DECL_NFEA_UNSPEC 0
#define HAVE_DECL_PTP_PF_EXTTS 0
#define HAVE_DECL_PTP_PF_NONE 0
#define HAVE_DECL_PTP_PF_PEROUT 0
#define HAVE_DECL_PTP_PF_PHYSYNC 0
#define HAVE_DECL_PTRACE_PEEKUSER 1
#define HAVE_DECL_PTRACE_POKEUSER 1
#define HAVE_DECL_P_ALL 1
#define HAVE_DECL_P_PGID 1
#define HAVE_DECL_P_PID 1
#define HAVE_DECL_P_PIDFD 1
#define HAVE_DECL_SYS_ERRLIST 0
#define HAVE_DECL_TCA_ACT_COOKIE 1
#define HAVE_DECL_TCA_ACT_FLAGS 1
#define HAVE_DECL_TCA_ACT_HW_STATS 1
#define HAVE_DECL_TCA_ACT_INDEX 1
#define HAVE_DECL_TCA_ACT_IN_HW_COUNT 1
#define HAVE_DECL_TCA_ACT_KIND 1
#define HAVE_DECL_TCA_ACT_OPTIONS 1
#define HAVE_DECL_TCA_ACT_PAD 1
#define HAVE_DECL_TCA_ACT_STATS 1
#define HAVE_DECL_TCA_ACT_UNSPEC 1
#define HAVE_DECL_TCA_ACT_USED_HW_STATS 1
#define HAVE_DECL_XFRM_MSG_ACQUIRE 1
#define HAVE_DECL_XFRM_MSG_ALLOCSPI 1
#define HAVE_DECL_XFRM_MSG_DELPOLICY 1
#define HAVE_DECL_XFRM_MSG_DELSA 1
#define HAVE_DECL_XFRM_MSG_EXPIRE 1
#define HAVE_DECL_XFRM_MSG_FLUSHPOLICY 1
#define HAVE_DECL_XFRM_MSG_FLUSHSA 1
#define HAVE_DECL_XFRM_MSG_GETAE 1
#define HAVE_DECL_XFRM_MSG_GETDEFAULT 1
#define HAVE_DECL_XFRM_MSG_GETPOLICY 1
#define HAVE_DECL_XFRM_MSG_GETSA 1
#define HAVE_DECL_XFRM_MSG_GETSADINFO 1
#define HAVE_DECL_XFRM_MSG_GETSPDINFO 1
#define HAVE_DECL_XFRM_MSG_MAPPING 1
#define HAVE_DECL_XFRM_MSG_MIGRATE 1
#define HAVE_DECL_XFRM_MSG_NEWAE 1
#define HAVE_DECL_XFRM_MSG_NEWPOLICY 1
#define HAVE_DECL_XFRM_MSG_NEWSA 1
#define HAVE_DECL_XFRM_MSG_NEWSADINFO 1
#define HAVE_DECL_XFRM_MSG_NEWSPDINFO 1
#define HAVE_DECL_XFRM_MSG_POLEXPIRE 1
#define HAVE_DECL_XFRM_MSG_REPORT 1
#define HAVE_DECL_XFRM_MSG_SETDEFAULT 1
#define HAVE_DECL_XFRM_MSG_UPDPOLICY 1
#define HAVE_DECL_XFRM_MSG_UPDSA 1
/* #undef HAVE_DEMANGLE_H */
#define HAVE_DLADDR 1
/* #undef HAVE_ELFUTILS_LIBDWFL_H */
#define HAVE_ELF_H 1
#define HAVE_FALLOCATE 1
#define HAVE_FANOTIFY_MARK 1
/* #undef HAVE_FCNTL64 */
/* #undef HAVE_FOPEN64 */
#define HAVE_FORK 1
#define HAVE_FPUTS_UNLOCKED 1
#define HAVE_FSTATAT 1
#define HAVE_FTRUNCATE 1
#define HAVE_FUTIMENS 1
#define HAVE_GCOV_H 1
/* #undef HAVE_GNU_STUBS */
/* #undef HAVE_GNU_STUBS_32_H */
/* #undef HAVE_GNU_STUBS_X32_H */
#define HAVE_ICONV_H 1
#define HAVE_ICONV_OPEN 1
#define HAVE_IF_INDEXTONAME 1
#define HAVE_INTTYPES_H 1
/* #undef HAVE_LIBIBERTY_DEMANGLE_H */
/* #undef HAVE_LIBUNWIND_PTRACE_H */
#define HAVE_LINUX_BPF_H 1
#define HAVE_LINUX_IF_ALG_H 1
#define HAVE_LINUX_IF_XDP_H 1
#define HAVE_LINUX_IPC_H 1
/* #undef HAVE_LINUX_IPX_H */
#define HAVE_LINUX_KVM_H 1
#define HAVE_LINUX_NETFILTER_ARP_ARP_TABLES_H 1
#define HAVE_LINUX_NETFILTER_BRIDGE_EBTABLES_H 1
#define HAVE_LINUX_NETFILTER_IPV4_IP_TABLES_H 1
#define HAVE_LINUX_NETFILTER_IPV6_IP6_TABLES_H 1
#define HAVE_LINUX_NFC_H 1
#define HAVE_LINUX_QRTR_H 1
#define HAVE_LINUX_RXRPC_H 1
#define HAVE_LINUX_VM_SOCKETS_H 1
/* #undef HAVE_M32_MPERS */
/* #undef HAVE_M32_SELINUX_RUNTIME */
/* #undef HAVE_M32_STRUCT_STAT */
/* #undef HAVE_M32_STRUCT_STAT64 */
/* #undef HAVE_M32_STRUCT_STAT64_ST_MTIME_NSEC */
/* #undef HAVE_M32_STRUCT_STAT_ST_MTIME_NSEC */
#define HAVE_MEMORY_H 1
#define HAVE_MEMPCPY 1
#define HAVE_MQUEUE_H 1
/* #undef HAVE_MX32_MPERS */
/* #undef HAVE_MX32_SELINUX_RUNTIME */
/* #undef HAVE_MX32_STRUCT_STAT */
/* #undef HAVE_MX32_STRUCT_STAT64 */
/* #undef HAVE_MX32_STRUCT_STAT64_ST_MTIME_NSEC */
/* #undef HAVE_MX32_STRUCT_STAT_ST_MTIME_NSEC */
/* #undef HAVE_NETINET_SCTP_H */
#define HAVE_NETINET_TCP_H 1
#define HAVE_NETINET_UDP_H 1
/* #undef HAVE_NETIPX_IPX_H */
/* #undef HAVE_OPEN64 */
#define HAVE_OPEN_MEMSTREAM 1
#define HAVE_PATHS_H 1
#define HAVE_PREADV 1
#define HAVE_PROCESS_VM_READV 1
#define HAVE_PROCESS_VM_WRITEV 1
#define HAVE_PROGRAM_INVOCATION_NAME 1
#define HAVE_PWRITEV 1
#define HAVE_READAHEAD 1
/* #undef HAVE_S390_COMPAT_REGS */
#define HAVE_SCSI_SG_H 1
/* #undef HAVE_SELINUX_RUNTIME */
/* #undef HAVE_SELINUX_SELINUX_H */
#define HAVE_SIGINFO_T_SI_ADDR_LSB 1
#define HAVE_SIGINFO_T_SI_LOWER 1
#define HAVE_SIGINFO_T_SI_OVERRUN 1
/* #undef HAVE_SIGINFO_T_SI_PERF_DATA */
/* #undef HAVE_SIGINFO_T_SI_PERF_FLAGS */
/* #undef HAVE_SIGINFO_T_SI_PERF_TYPE */
#define HAVE_SIGINFO_T_SI_PKEY 1
#define HAVE_SIGINFO_T_SI_SYSCALL 1
#define HAVE_SIGINFO_T_SI_TIMERID 1
/* #undef HAVE_SIGINFO_T_SI_TRAPNO */
#define HAVE_SIGINFO_T_SI_UPPER 1
#define HAVE_SIGNALFD 1
#define HAVE_SIG_ATOMIC_T 1
#define HAVE_STATIC_ASSERT 1
#define HAVE_STDINT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STPCPY 1
#define HAVE_STRERROR 1
#define HAVE_STRINGS_H 1
#define HAVE_STRING_H 1
#define HAVE_STRNDUP 1
#define HAVE_STRUCT_BPF_INSN 1
#define HAVE_STRUCT_BPF_MAP_INFO 1
#define HAVE_STRUCT_BPF_MAP_INFO_BTF_ID 1
#define HAVE_STRUCT_BPF_MAP_INFO_BTF_KEY_TYPE_ID 1
#define HAVE_STRUCT_BPF_MAP_INFO_BTF_VALUE_TYPE_ID 1
#define HAVE_STRUCT_BPF_MAP_INFO_BTF_VMLINUX_VALUE_TYPE_ID 1
#define HAVE_STRUCT_BPF_MAP_INFO_ID 1
#define HAVE_STRUCT_BPF_MAP_INFO_IFINDEX 1
#define HAVE_STRUCT_BPF_MAP_INFO_KEY_SIZE 1
#define HAVE_STRUCT_BPF_MAP_INFO_MAP_EXTRA 1
#define HAVE_STRUCT_BPF_MAP_INFO_MAP_FLAGS 1
#define HAVE_STRUCT_BPF_MAP_INFO_MAX_ENTRIES 1
#define HAVE_STRUCT_BPF_MAP_INFO_NAME 1
/* #undef HAVE_STRUCT_BPF_MAP_INFO_PAD */
#define HAVE_STRUCT_BPF_MAP_INFO_TYPE 1
#define HAVE_STRUCT_BPF_MAP_INFO_VALUE_SIZE 1
#define HAVE_STRUCT_BPF_PROG_INFO 1
#define HAVE_STRUCT_BPF_PROG_INFO_BTF_ID 1
#define HAVE_STRUCT_BPF_PROG_INFO_CREATED_BY_UID 1
#define HAVE_STRUCT_BPF_PROG_INFO_FUNC_INFO 1
#define HAVE_STRUCT_BPF_PROG_INFO_FUNC_INFO_REC_SIZE 1
#define HAVE_STRUCT_BPF_PROG_INFO_ID 1
#define HAVE_STRUCT_BPF_PROG_INFO_IFINDEX 1
#define HAVE_STRUCT_BPF_PROG_INFO_JITED_FUNC_LENS 1
#define HAVE_STRUCT_BPF_PROG_INFO_JITED_KSYMS 1
#define HAVE_STRUCT_BPF_PROG_INFO_JITED_LINE_INFO 1
#define HAVE_STRUCT_BPF_PROG_INFO_JITED_LINE_INFO_REC_SIZE 1
#define HAVE_STRUCT_BPF_PROG_INFO_JITED_PROG_INSNS 1
#define HAVE_STRUCT_BPF_PROG_INFO_JITED_PROG_LEN 1
#define HAVE_STRUCT_BPF_PROG_INFO_LINE_INFO 1
#define HAVE_STRUCT_BPF_PROG_INFO_LINE_INFO_REC_SIZE 1
#define HAVE_STRUCT_BPF_PROG_INFO_LOAD_TIME 1
#define HAVE_STRUCT_BPF_PROG_INFO_MAP_IDS 1
#define HAVE_STRUCT_BPF_PROG_INFO_NAME 1
#define HAVE_STRUCT_BPF_PROG_INFO_NR_FUNC_INFO 1
#define HAVE_STRUCT_BPF_PROG_INFO_NR_JITED_FUNC_LENS 1
#define HAVE_STRUCT_BPF_PROG_INFO_NR_JITED_KSYMS 1
#define HAVE_STRUCT_BPF_PROG_INFO_NR_JITED_LINE_INFO 1
#define HAVE_STRUCT_BPF_PROG_INFO_NR_LINE_INFO 1
#define HAVE_STRUCT_BPF_PROG_INFO_NR_MAP_IDS 1
#define HAVE_STRUCT_BPF_PROG_INFO_NR_PROG_TAGS 1
#define HAVE_STRUCT_BPF_PROG_INFO_PROG_TAGS 1
#define HAVE_STRUCT_BPF_PROG_INFO_RECURSION_MISSES 1
#define HAVE_STRUCT_BPF_PROG_INFO_RUN_CNT 1
#define HAVE_STRUCT_BPF_PROG_INFO_RUN_TIME_NS 1
#define HAVE_STRUCT_BPF_PROG_INFO_TAG 1
#define HAVE_STRUCT_BPF_PROG_INFO_TYPE 1
#define HAVE_STRUCT_BPF_PROG_INFO_VERIFIED_INSNS 1
#define HAVE_STRUCT_BPF_PROG_INFO_XLATED_PROG_INSNS 1
#define HAVE_STRUCT_BPF_PROG_INFO_XLATED_PROG_LEN 1
/* #undef HAVE_STRUCT_IA64_FPREG */
#define HAVE_STRUCT_IOCB_AIO_FLAGS 1
#define HAVE_STRUCT_IOCB_AIO_RW_FLAGS 1
#define HAVE_STRUCT_KBDIACRSUC 1
#define HAVE_STRUCT_KBDIACRUC 1
#define HAVE_STRUCT_KVM_CPUID2 1
#define HAVE_STRUCT_KVM_REGS 1
#define HAVE_STRUCT_KVM_SREGS 1
#define HAVE_STRUCT_KVM_USERSPACE_MEMORY_REGION 1
#define HAVE_STRUCT_MMSGHDR 1
/* #undef HAVE_STRUCT_PTRACE_PEEKSIGINFO_ARGS */
#define HAVE_STRUCT_PTRACE_SYSCALL_INFO 1
/* #undef HAVE_STRUCT_PT_ALL_USER_REGS */
#define HAVE_STRUCT_SIGCONTEXT 1
#define HAVE_STRUCT_SOCKADDR_ALG_NEW 1
/* #undef HAVE_STRUCT_SOCKADDR_HCI_HCI_CHANNEL */
/* #undef HAVE_STRUCT_SOCKADDR_L2_L2_BDADDR_TYPE */
#define HAVE_STRUCT_SOCKADDR_STORAGE 1
#define HAVE_STRUCT_SOCKADDR_VM 1
#define HAVE_STRUCT_SOCKADDR_VM_SVM_FLAGS 1
#define HAVE_STRUCT_SOCKADDR_XDP 1
/* #undef HAVE_STRUCT_STAT64 */
/* #undef HAVE_STRUCT_STAT64_ST_MTIME_NSEC */
#define HAVE_STRUCT_STATFS 1
#define HAVE_STRUCT_STATFS64 1
#define HAVE_STRUCT_STATFS64_F_FLAGS 1
#define HAVE_STRUCT_STATFS64_F_FRSIZE 1
#define HAVE_STRUCT_STATFS64_F_FSID_VAL 1
/* #undef HAVE_STRUCT_STATFS64_F_FSID___VAL */
#define HAVE_STRUCT_STATFS_F_FLAGS 1
#define HAVE_STRUCT_STATFS_F_FRSIZE 1
#define HAVE_STRUCT_STATFS_F_FSID_VAL 1
/* #undef HAVE_STRUCT_STATFS_F_FSID___VAL */
#define HAVE_STRUCT_STAT_ST_MTIME_NSEC 1
#define HAVE_STRUCT_TCP_DIAG_MD5SIG 1
#define HAVE_STRUCT_TERMIOS2 1
/* #undef HAVE_STRUCT_TERMIOS_C_ISPEED */
/* #undef HAVE_STRUCT_TERMIOS_C_OSPEED */
#define HAVE_STRUCT_USER_DESC 1
#define HAVE_STRUCT_USER_DESC_LM 1
#define HAVE_STRUCT_UTSNAME_DOMAINNAME 1
/* #undef HAVE_STRUCT___AIO_SIGSET */
#define HAVE_STRUCT___KERNEL_SOCK_TIMEVAL 1
#define HAVE_STRUCT___KERNEL_TIMESPEC 1
#define HAVE_STRUCT___OLD_KERNEL_STAT 1
#define HAVE_STRUCT___PTRACE_SYSCALL_INFO 1
#define HAVE_SYNC_FILE_RANGE 1
#define HAVE_SYS_EVENTFD_H 1
#define HAVE_SYS_FANOTIFY_H 1
#define HAVE_SYS_IPC_H 1
#define HAVE_SYS_QUOTA_H 1
#define HAVE_SYS_SIGNALFD_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_XATTR_H 1
#define HAVE_TYPEOF 1
#define HAVE_UNION_BPF_ATTR_ATTACH_BPF_FD 1
#define HAVE_UNION_BPF_ATTR_ATTACH_BTF_ID 1
#define HAVE_UNION_BPF_ATTR_ATTACH_FLAGS 1
#define HAVE_UNION_BPF_ATTR_ATTACH_PROG_FD 1
#define HAVE_UNION_BPF_ATTR_ATTACH_TYPE 1
#define HAVE_UNION_BPF_ATTR_BATCH_COUNT 1
#define HAVE_UNION_BPF_ATTR_BATCH_ELEM_FLAGS 1
#define HAVE_UNION_BPF_ATTR_BATCH_FLAGS 1
#define HAVE_UNION_BPF_ATTR_BATCH_IN_BATCH 1
#define HAVE_UNION_BPF_ATTR_BATCH_KEYS 1
#define HAVE_UNION_BPF_ATTR_BATCH_MAP_FD 1
#define HAVE_UNION_BPF_ATTR_BATCH_OUT_BATCH 1
#define HAVE_UNION_BPF_ATTR_BATCH_VALUES 1
#define HAVE_UNION_BPF_ATTR_BPF_FD 1
#define HAVE_UNION_BPF_ATTR_BTF 1
#define HAVE_UNION_BPF_ATTR_BTF_FD 1
#define HAVE_UNION_BPF_ATTR_BTF_ID 1
#define HAVE_UNION_BPF_ATTR_BTF_KEY_TYPE_ID 1
#define HAVE_UNION_BPF_ATTR_BTF_LOG_BUF 1
#define HAVE_UNION_BPF_ATTR_BTF_LOG_LEVEL 1
#define HAVE_UNION_BPF_ATTR_BTF_LOG_SIZE 1
#define HAVE_UNION_BPF_ATTR_BTF_SIZE 1
#define HAVE_UNION_BPF_ATTR_BTF_VALUE_TYPE_ID 1
#define HAVE_UNION_BPF_ATTR_BTF_VMLINUX_VALUE_TYPE_ID 1
/* #undef HAVE_UNION_BPF_ATTR_DUMMY */
#define HAVE_UNION_BPF_ATTR_EXPECTED_ATTACH_TYPE 1
#define HAVE_UNION_BPF_ATTR_FD_ARRAY 1
#define HAVE_UNION_BPF_ATTR_FILE_FLAGS 1
#define HAVE_UNION_BPF_ATTR_FLAGS 1
#define HAVE_UNION_BPF_ATTR_FUNC_INFO 1
#define HAVE_UNION_BPF_ATTR_FUNC_INFO_CNT 1
#define HAVE_UNION_BPF_ATTR_FUNC_INFO_REC_SIZE 1
#define HAVE_UNION_BPF_ATTR_INFO_BPF_FD 1
#define HAVE_UNION_BPF_ATTR_INFO_INFO 1
#define HAVE_UNION_BPF_ATTR_INFO_INFO_LEN 1
#define HAVE_UNION_BPF_ATTR_INNER_MAP_FD 1
#define HAVE_UNION_BPF_ATTR_INSNS 1
#define HAVE_UNION_BPF_ATTR_INSN_CNT 1
#define HAVE_UNION_BPF_ATTR_KERN_VERSION 1
#define HAVE_UNION_BPF_ATTR_KEY 1
#define HAVE_UNION_BPF_ATTR_KEY_SIZE 1
#define HAVE_UNION_BPF_ATTR_LICENSE 1
#define HAVE_UNION_BPF_ATTR_LINE_INFO 1
#define HAVE_UNION_BPF_ATTR_LINE_INFO_CNT 1
#define HAVE_UNION_BPF_ATTR_LINE_INFO_REC_SIZE 1
/* #undef HAVE_UNION_BPF_ATTR_LINK_CREATE_ADDRS */
#define HAVE_UNION_BPF_ATTR_LINK_CREATE_ATTACH_TYPE 1
/* #undef HAVE_UNION_BPF_ATTR_LINK_CREATE_BPF_COOKIE */
/* #undef HAVE_UNION_BPF_ATTR_LINK_CREATE_CNT */
/* #undef HAVE_UNION_BPF_ATTR_LINK_CREATE_COOKIES */
#define HAVE_UNION_BPF_ATTR_LINK_CREATE_FLAGS 1
#define HAVE_UNION_BPF_ATTR_LINK_CREATE_ITER_INFO 1
#define HAVE_UNION_BPF_ATTR_LINK_CREATE_ITER_INFO_LEN 1
#define HAVE_UNION_BPF_ATTR_LINK_CREATE_KPROBE_MULTI 1
#define HAVE_UNION_BPF_ATTR_LINK_CREATE_PERF_EVENT 1
#define HAVE_UNION_BPF_ATTR_LINK_CREATE_PROG_FD 1
/* #undef HAVE_UNION_BPF_ATTR_LINK_CREATE_SYMS */
#define HAVE_UNION_BPF_ATTR_LINK_CREATE_TARGET_BTF_ID 1
#define HAVE_UNION_BPF_ATTR_LINK_CREATE_TARGET_FD 1
#define HAVE_UNION_BPF_ATTR_LINK_ID 1
#define HAVE_UNION_BPF_ATTR_LINK_UPDATE_FLAGS 1
#define HAVE_UNION_BPF_ATTR_LINK_UPDATE_LINK_FD 1
#define HAVE_UNION_BPF_ATTR_LINK_UPDATE_NEW_PROG_FD 1
#define HAVE_UNION_BPF_ATTR_LINK_UPDATE_OLD_PROG_FD 1
#define HAVE_UNION_BPF_ATTR_LOG_BUF 1
#define HAVE_UNION_BPF_ATTR_LOG_LEVEL 1
#define HAVE_UNION_BPF_ATTR_LOG_SIZE 1
#define HAVE_UNION_BPF_ATTR_MAP_EXTRA 1
#define HAVE_UNION_BPF_ATTR_MAP_FD 1
#define HAVE_UNION_BPF_ATTR_MAP_FLAGS 1
#define HAVE_UNION_BPF_ATTR_MAP_ID 1
#define HAVE_UNION_BPF_ATTR_MAP_IFINDEX 1
#define HAVE_UNION_BPF_ATTR_MAP_NAME 1
#define HAVE_UNION_BPF_ATTR_MAP_TYPE 1
#define HAVE_UNION_BPF_ATTR_MAX_ENTRIES 1
#define HAVE_UNION_BPF_ATTR_NEXT_ID 1
#define HAVE_UNION_BPF_ATTR_NEXT_KEY 1
#define HAVE_UNION_BPF_ATTR_NUMA_NODE 1
#define HAVE_UNION_BPF_ATTR_OPEN_FLAGS 1
/* #undef HAVE_UNION_BPF_ATTR_PAD */
#define HAVE_UNION_BPF_ATTR_PATHNAME 1
#define HAVE_UNION_BPF_ATTR_PROG_BTF_FD 1
#define HAVE_UNION_BPF_ATTR_PROG_FLAGS 1
#define HAVE_UNION_BPF_ATTR_PROG_ID 1
#define HAVE_UNION_BPF_ATTR_PROG_IFINDEX 1
#define HAVE_UNION_BPF_ATTR_PROG_NAME 1
#define HAVE_UNION_BPF_ATTR_PROG_TYPE 1
#define HAVE_UNION_BPF_ATTR_QUERY_ATTACH_FLAGS 1
#define HAVE_UNION_BPF_ATTR_QUERY_ATTACH_TYPE 1
#define HAVE_UNION_BPF_ATTR_QUERY_PROG_CNT 1
#define HAVE_UNION_BPF_ATTR_QUERY_PROG_IDS 1
#define HAVE_UNION_BPF_ATTR_QUERY_QUERY_FLAGS 1
#define HAVE_UNION_BPF_ATTR_QUERY_TARGET_FD 1
#define HAVE_UNION_BPF_ATTR_RAW_TRACEPOINT_NAME 1
#define HAVE_UNION_BPF_ATTR_RAW_TRACEPOINT_PROG_FD 1
#define HAVE_UNION_BPF_ATTR_REPLACE_BPF_FD 1
#define HAVE_UNION_BPF_ATTR_START_ID 1
#define HAVE_UNION_BPF_ATTR_TARGET_FD 1
#define HAVE_UNION_BPF_ATTR_TASK_FD_QUERY_BUF 1
#define HAVE_UNION_BPF_ATTR_TASK_FD_QUERY_BUF_LEN 1
#define HAVE_UNION_BPF_ATTR_TASK_FD_QUERY_FD 1
#define HAVE_UNION_BPF_ATTR_TASK_FD_QUERY_FD_TYPE 1
#define HAVE_UNION_BPF_ATTR_TASK_FD_QUERY_FLAGS 1
#define HAVE_UNION_BPF_ATTR_TASK_FD_QUERY_PID 1
#define HAVE_UNION_BPF_ATTR_TASK_FD_QUERY_PROBE_ADDR 1
#define HAVE_UNION_BPF_ATTR_TASK_FD_QUERY_PROBE_OFFSET 1
#define HAVE_UNION_BPF_ATTR_TASK_FD_QUERY_PROG_ID 1
#define HAVE_UNION_BPF_ATTR_TEST_BATCH_SIZE 1
#define HAVE_UNION_BPF_ATTR_TEST_CPU 1
#define HAVE_UNION_BPF_ATTR_TEST_CTX_IN 1
#define HAVE_UNION_BPF_ATTR_TEST_CTX_OUT 1
#define HAVE_UNION_BPF_ATTR_TEST_CTX_SIZE_IN 1
#define HAVE_UNION_BPF_ATTR_TEST_CTX_SIZE_OUT 1
#define HAVE_UNION_BPF_ATTR_TEST_DATA_IN 1
#define HAVE_UNION_BPF_ATTR_TEST_DATA_OUT 1
#define HAVE_UNION_BPF_ATTR_TEST_DATA_SIZE_IN 1
#define HAVE_UNION_BPF_ATTR_TEST_DATA_SIZE_OUT 1
#define HAVE_UNION_BPF_ATTR_TEST_DURATION 1
#define HAVE_UNION_BPF_ATTR_TEST_FLAGS 1
#define HAVE_UNION_BPF_ATTR_TEST_PROG_FD 1
#define HAVE_UNION_BPF_ATTR_TEST_REPEAT 1
#define HAVE_UNION_BPF_ATTR_TEST_RETVAL 1
#define HAVE_UNION_BPF_ATTR_VALUE 1
#define HAVE_UNION_BPF_ATTR_VALUE_SIZE 1
#define HAVE_UNISTD_H 1
/* #undef HAVE_USTAT_H */
/* #undef HAVE__STATIC_ASSERT */
/* probe HAVE___BUILTIN_POPCOUNT */
#define HAVE___KERNEL_LONG_T 1
#define HAVE___KERNEL_ULONG_T 1
/* #undef HPPA */
/* #undef I386 */
/* #undef IA64 */
/* #undef LINUX_MIPSN32 */
/* #undef LINUX_MIPSN64 */
/* #undef LINUX_MIPSO32 */
/* #undef LOONGARCH64 */
/* #undef M32_SIZEOF_KERNEL_LONG_T */
/* #undef M32_SIZEOF_LONG */
/* #undef M32_SIZEOF_STRUCT_MSQID64_DS */
/* #undef M68K */
/* #undef METAG */
/* #undef MICROBLAZE */
/* #undef MIPS */
/* #undef MX32_SIZEOF_KERNEL_LONG_T */
/* #undef MX32_SIZEOF_LONG */
/* #undef MX32_SIZEOF_STRUCT_MSQID64_DS */
/* #undef NIOS2 */
/* #undef OR1K */
#define PACKAGE "strace"
#define PACKAGE_BUGREPORT "strace-devel@lists.strace.io"
#define PACKAGE_NAME "strace"
#define PACKAGE_STRING "strace 6.4"
#define PACKAGE_TARNAME "strace"
#define PACKAGE_URL "https://strace.io"
#define PACKAGE_VERSION "6.4"
/* #undef POWERPC */
/* #undef POWERPC64 */
/* #undef POWERPC64LE */
/* #undef RISCV64 */
/* #undef S390 */
/* #undef S390X */
/* #undef SH */
/* #undef SH64 */
#define SIZEOF_KERNEL_LONG_T 8
#define SIZEOF_LONG 8
#define SIZEOF_LONG_LONG 8
#define SIZEOF_OFF_T 8
#define SIZEOF_STRUCT_I64_I32 16
#define SIZEOF_STRUCT_MSQID64_DS 120
#define SLM_MANPAGE_DATE "2022-01-01"
/* #undef SPARC */
/* #undef SPARC64 */
#define STDC_HEADERS 1
#define STRACE_MANPAGE_DATE "2023-06-11"
/* #undef TILE */
/* #undef USE_DEMANGLE */
/* #undef USE_LIBDW */
/* #undef USE_LIBUNWIND */
#ifndef _ALL_SOURCE
# define _ALL_SOURCE 1
#endif
#ifndef _GNU_SOURCE
# define _GNU_SOURCE 1
#endif
#ifndef _POSIX_PTHREAD_SEMANTICS
# define _POSIX_PTHREAD_SEMANTICS 1
#endif
#ifndef _TANDEM_SOURCE
# define _TANDEM_SOURCE 1
#endif
#ifndef __EXTENSIONS__
# define __EXTENSIONS__ 1
#endif
/* #undef USE_UNWINDER */
#define VERSION "6.4"
#if defined AC_APPLE_UNIVERSAL_BUILD
# if defined __BIG_ENDIAN__
#  define WORDS_BIGENDIAN 1
# endif
#else
# ifndef WORDS_BIGENDIAN
/* #  undef WORDS_BIGENDIAN */
# endif
#endif
/* #undef X32 */
#define X86_64 1
/* #undef XTENSA */
/* #undef _MINIX */
/* #undef _POSIX_1_SOURCE */
/* #undef _POSIX_SOURCE */
/* #undef gid_t */
/* #undef typeof */
/* #undef uid_t */
