#define CONFIG_BACKEND_FILE
#define CONFIG_CTRL_IFACE
#define CONFIG_CTRL_IFACE_DIR "/run/wpa_supplicant"
#define CONFIG_CTRL_IFACE_UNIX
#define CONFIG_DRIVER_NL80211
#define CONFIG_ELOOP_POLL
#define CONFIG_LIBNL20
#define CONFIG_LIBNL32
#define CONFIG_NO_CONFIG_BLOBS
#define CONFIG_NO_CONFIG_WRITE
#define CONFIG_PEERKEY
#define CONFIG_SHA256
#define CONFIG_SME
#define CONFIG_TDLS
