#line 2 "webidl-lexer.c"

#line 4 "webidl-lexer.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer webidl__create_buffer
#define yy_delete_buffer webidl__delete_buffer
#define yy_flex_debug webidl__flex_debug
#define yy_init_buffer webidl__init_buffer
#define yy_flush_buffer webidl__flush_buffer
#define yy_load_buffer_state webidl__load_buffer_state
#define yy_switch_to_buffer webidl__switch_to_buffer
#define yyin webidl_in
#define yyleng webidl_leng
#define yylex webidl_lex
#define yylineno webidl_lineno
#define yyout webidl_out
#define yyrestart webidl_restart
#define yytext webidl_text
#define yywrap webidl_wrap
#define yyalloc webidl_alloc
#define yyrealloc webidl_realloc
#define yyfree webidl_free

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 2
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE webidl_restart(webidl_in  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int webidl_leng;

extern FILE *webidl_in, *webidl_out;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE webidl_lex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-webidl_lineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < webidl_leng; ++yyl )\
                    if ( webidl_text[yyl] == '\n' )\
                        --webidl_lineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --webidl_lineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up webidl_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up webidl_text again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via webidl_restart()), so that the user can continue scanning by
	 * just pointing webidl_in at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when webidl_text is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int webidl_leng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow webidl_wrap()'s to do buffer switches
 * instead of setting up a fresh webidl_in.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void webidl_restart (FILE *input_file  );
void webidl__switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE webidl__create_buffer (FILE *file,int size  );
void webidl__delete_buffer (YY_BUFFER_STATE b  );
void webidl__flush_buffer (YY_BUFFER_STATE b  );
void webidl_push_buffer_state (YY_BUFFER_STATE new_buffer  );
void webidl_pop_buffer_state (void );

static void webidl_ensure_buffer_stack (void );
static void webidl__load_buffer_state (void );
static void webidl__init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER webidl__flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE webidl__scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE webidl__scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE webidl__scan_bytes (yyconst char *bytes,int len  );

void *webidl_alloc (yy_size_t  );
void *webidl_realloc (void *,yy_size_t  );
void webidl_free (void *  );

#define yy_new_buffer webidl__create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        webidl_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            webidl__create_buffer(webidl_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        webidl_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            webidl__create_buffer(webidl_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define webidl_wrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP

typedef flex_uint8_t YY_CHAR;

FILE *webidl_in = NULL, *webidl_out = NULL;

typedef int yy_state_type;

extern int webidl_lineno;

int webidl_lineno = 1;

extern char *webidl_text;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr webidl_text

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yynoreturn yy_fatal_error (yyconst char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up webidl_text.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	webidl_leng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 64
#define YY_END_OF_BUFFER 65
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[407] =
    {   0,
        0,    0,    0,    0,   65,   60,    1,    2,    1,   60,
       60,   60,   60,   52,   52,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   60,   60,
       60,   60,    1,    1,   60,   60,   60,   60,   60,   62,
       64,   63,   62,   61,    0,   56,    0,   52,    0,   55,
        0,   58,   55,   53,    0,    0,   52,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   37,   51,

       51,   51,   51,   51,   51,   51,   51,   51,    1,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    1,    0,    0,    0,    0,    0,   62,    0,   61,
       62,    0,    0,    0,   25,    0,    0,    0,   55,    0,
        0,   55,   54,   51,   51,   51,   51,   29,   51,   51,
       30,   51,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,    1,    2,
        0,    0,    0,    0,    0,    0,    1,    0,    0,    0,

       55,   57,    0,   55,   51,   51,   26,   51,   51,   51,
       51,   51,    4,   51,   51,   51,   51,   51,   51,   12,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   34,
       35,   51,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   41,   51,   51,   51,   43,    0,    0,    0,
       51,   51,   51,   51,   51,   51,   51,   51,    8,   51,
       51,   51,   51,   51,   32,   33,   51,   51,   51,   51,
       51,   51,   51,    5,   51,   51,   51,   51,   51,   51,
       40,   51,   51,   51,   51,   51,    0,    0,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   31,

       51,   14,   51,   51,   51,   51,   51,   36,   51,   51,
       51,   51,   51,   20,   21,   51,   51,   51,   51,    0,
       51,   51,   51,   51,   45,   51,    3,   51,    9,   10,
       51,   51,   51,   16,   51,   51,   51,   51,   51,   19,
       51,   51,   51,   51,   23,   51,   51,    0,   51,   51,
       28,   51,   51,    7,   51,   51,   51,   51,   46,   51,
       51,   38,   44,   48,   39,   51,   51,   42,   59,   51,
       27,   51,    6,   51,   13,   51,   17,   51,   51,   51,
       51,   51,   51,   11,   15,   51,   51,   51,   51,   49,
       51,   51,   51,   22,   51,   51,   18,   51,   24,   51,

       51,   51,   47,   51,   50,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        4,    4,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    6,    1,    7,    8,    1,    1,    1,    9,    1,
        1,   10,   11,    1,   11,   12,   13,   14,   15,   15,
       15,   15,   15,   15,   15,   15,   16,    1,    1,    1,
        1,    1,    1,    1,   17,   17,   18,   19,   20,   17,
       21,   21,   22,   21,   21,   21,   23,   24,   25,   26,
       21,   21,   27,   21,   21,   21,   21,   28,   21,   21,
        1,   29,    1,    1,   21,    1,   30,   31,   32,   33,

       34,   35,   36,   37,   38,   39,   40,   41,   42,   43,
       44,   45,   46,   47,   48,   49,   50,   51,   21,   52,
       53,   21,    1,    1,    1,    1,    1,   54,   55,   56,
       56,   56,   56,   56,   56,   56,   56,   56,    1,    1,
        1,   57,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,   58,    1,    1,    1,    1,   59,   60,
        1,    1,    1,    1,    1,    1,    1,   61,   62,    1,
        1,    1,    1,    1,   63,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,   64,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,   65,   66,   67,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[68] =
    {   0,
        1,    2,    3,    1,    4,    1,    2,    1,    1,    1,
        1,    1,    1,    5,    5,    5,    5,    5,    5,    5,
        6,    6,    6,    6,    6,    6,    6,    6,    1,    5,
        5,    5,    5,    5,    5,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[413] =
    {   0,
        0,   66,   73,   75,  659,  660,  660,  660,  660,   62,
       68,   73,   80,   82,   89,    0,  614,   70,  614,  626,
      608,   43,   54,   78,   77,   74,   83,  620,   86,   93,
      603,  107,  622,  617,  106,   59,  607,  605,  588,   13,
       64,  593,  140,  145,  608,  585,   98,  105,  590,    0,
      155,  660,  161,  660,  107,  660,  127,  158,  631,  166,
      632,  660,  169,  150,  179,    0,  201,    0,  598,  617,
      590,  603,  145,  593,  583,  586,  590,  584,  591,  588,
      596,  588,  596,  577,  576,  593,  583,  579,  573,  576,
      139,  586,  583,  575,  576,  577,  566,  565,    0,  566,

      120,  150,  568,  161,  561,  565,  150,  571,  660,  554,
      550,  164,  547,  551,  226,  566,  543,  164,  147,  548,
      558,  234,  546,  542,  189,  539,  543,    0,  247,  660,
      253,  232,  295,  317,  660,  251,  586,  582,  254,  261,
      232,  242,    0,  546,  566,  558,  553,    0,  556,  547,
        0,  541,  546,  552,  544,  536,  553,  548,  532,  549,
      537,  544,  529,  546,  526,  533,  539,  538,  524,  540,
      533,  527,  533,  532,  527,  515,  530,  512,  511,  511,
      512,  509,  519,  522,  521,  520,  515,  519,  660,  660,
      497,  493,  224,  490,  494,  515,  314,  368,  390,  267,

      270,  660,  280,  289,  497,  496,    0,  501,  510,  504,
      503,  506,    0,  508,  489,  488,  487,  497,  493,    0,
      488,  498,  482,  496,  495,  481,  480,  496,  493,    0,
        0,  492,  474,  478,  483,  476,  481,  484,  483,  467,
      477,  471,    0,  480,  464,  475,    0,  351,  469,  412,
      462,  461,  469,  488,  457,  473,  473,  472,    0,  457,
      466,  455,  464,  448,    0,    0,  449,  453,  456,  458,
      461,  438,  441,    0,  446,  458,  444,  439,  442,  437,
        0,  451,  446,  447,  431,  436,  428,    0,  427,  438,
      426,  430,  430,  413,  414,  424,  394,  393,  396,    0,

      400,    0,  403,  387,  405,  393,  191,    0,  403,  378,
      373,  379,  380,    0,    0,  373,  362,  349,  361,  361,
      361,  349,  338,  347,    0,  340,    0,  337,    0,    0,
      346,  331,  331,    0,  341,  338,  341,  321,  328,    0,
      315,  334,  332,  330,    0,  326,  330,  328,  312,  324,
        0,  310,  322,    0,  307,  303,  296,  310,    0,  302,
      308,    0,    0,    0,    0,  303,  308,    0,  660,  295,
        0,  289,    0,  270,    0,  273,    0,  278,  270,  274,
      258,  259,  250,    0,    0,  255,  243,  224,  230,    0,
      213,  194,  206,    0,  200,  199,    0,  173,    0,  126,

      137,  101,    0,   73,    0,  660,  447,  453,  455,  461,
      467,   94
    } ;

static yyconst flex_int16_t yy_def[413] =
    {   0,
      406,    1,  407,  407,  406,  406,  406,  406,  406,  408,
      406,  406,  406,  406,  406,  409,  409,  409,  409,  409,
      409,  409,  409,  409,  409,  409,  409,  409,  409,  409,
      409,  409,  409,  409,  409,  409,  409,  409,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  410,
      406,  406,  410,  406,  408,  406,  408,  406,  406,  406,
      411,  406,  406,  406,  406,  412,  406,  409,  409,  409,
      409,  409,  409,  409,  409,  409,  409,  409,  409,  409,
      409,  409,  409,  409,  409,  409,  409,  409,  409,  409,
      409,  409,  409,  409,  409,  409,  409,  409,  409,  409,

      409,  409,  409,  409,  409,  409,  409,  409,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  410,  406,  406,
      410,  408,  408,  133,  406,  406,  411,  411,  406,  406,
      406,  406,  412,  409,  409,  409,  409,  409,  409,  409,
      409,  409,  409,  409,  409,  409,  409,  409,  409,  409,
      409,  409,  409,  409,  409,  409,  409,  409,  409,  409,
      409,  409,  409,  409,  409,  409,  409,  409,  409,  409,
      409,  409,  409,  409,  409,  409,  409,  409,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  133,  133,  406,

      406,  406,  406,  406,  409,  409,  409,  409,  409,  409,
      409,  409,  409,  409,  409,  409,  409,  409,  409,  409,
      409,  409,  409,  409,  409,  409,  409,  409,  409,  409,
      409,  409,  409,  409,  409,  409,  409,  409,  409,  409,
      409,  409,  409,  409,  409,  409,  409,  406,  406,  133,
      409,  409,  409,  409,  409,  409,  409,  409,  409,  409,
      409,  409,  409,  409,  409,  409,  409,  409,  409,  409,
      409,  409,  409,  409,  409,  409,  409,  409,  409,  409,
      409,  409,  409,  409,  409,  409,  406,  199,  409,  409,
      409,  409,  409,  409,  409,  409,  409,  409,  409,  409,

      409,  409,  409,  409,  409,  409,  409,  409,  409,  409,
      409,  409,  409,  409,  409,  409,  409,  409,  409,  406,
      409,  409,  409,  409,  409,  409,  409,  409,  409,  409,
      409,  409,  409,  409,  409,  409,  409,  409,  409,  409,
      409,  409,  409,  409,  409,  409,  409,  406,  409,  409,
      409,  409,  409,  409,  409,  409,  409,  409,  409,  409,
      409,  409,  409,  409,  409,  409,  409,  409,  406,  409,
      409,  409,  409,  409,  409,  409,  409,  409,  409,  409,
      409,  409,  409,  409,  409,  409,  409,  409,  409,  409,
      409,  409,  409,  409,  409,  409,  409,  409,  409,  409,

      409,  409,  409,  409,  409,    0,  406,  406,  406,  406,
      406,  406
    } ;

static yyconst flex_int16_t yy_nxt[728] =
    {   0,
        6,    7,    8,    9,    8,    7,   10,    6,    6,    6,
       11,   12,   13,   14,   15,   15,   16,   17,   18,   16,
       16,   19,   16,   20,   16,   21,   16,   16,    6,   22,
       23,   24,   25,   26,   27,   28,   16,   29,   16,   16,
       30,   16,   31,   32,   33,   16,   34,   35,   36,   37,
       38,   16,   16,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,   39,   40,   41,   42,   43,   56,   44,
      110,   43,  111,   45,   51,   52,   51,   52,   53,   54,
       53,   54,   58,   58,   59,   75,   60,   60,   60,   61,
       57,   76,   62,   63,   70,   64,   64,   77,  143,   71,

       63,   65,   67,   67,   67,  105,   78,   79,   65,   66,
       82,  106,   87,   56,   83,   65,   85,  112,  113,  405,
       84,   80,   65,   88,   81,   86,   93,   90,   91,   46,
       47,   48,   49,   66,   92,   57,   94,   96,   97,  102,
      132,  115,  103,  115,  404,  115,  115,  116,  115,  177,
      115,   98,  116,   99,  104,  123,  129,  124,  125,  126,
      129,  130,  129,   64,   64,  178,  131,  130,  148,   63,
      403,   67,   67,   67,  402,  167,  133,   65,  134,   60,
       60,   60,  139,  139,  139,  136,  149,  168,  140,  141,
      182,   65,  142,  142,  142,  179,  186,  187,  180,  136,

      193,  194,  140,  117,  118,  119,  120,  183,  117,  118,
      119,  120,   63,  401,   67,   67,   67,  189,  189,  189,
       65,  191,  337,  192,  190,  190,  189,  115,  338,  115,
      400,  115,  399,  116,   65,  115,  398,  115,   56,  115,
      397,  116,  197,  197,  197,  142,  142,  142,  129,  190,
      190,  197,  129,  130,  129,  142,  142,  142,  131,  130,
       57,  200,  396,  395,  201,  201,  201,  139,  139,  139,
      394,  203,  393,  140,  204,  204,  204,  248,  248,  248,
      201,  201,  201,  201,  201,  201,  248,  140,  392,  117,
      118,  119,  120,  204,  204,  204,  391,  117,  118,  119,

      120,   56,  204,  204,  204,  390,  389,  388,  198,  198,
      198,  198,  198,  198,  198,  115,  387,  115,  386,  115,
      385,  116,  384,   57,  198,  198,  198,  198,  198,  198,
      199,  199,  199,  199,  199,  199,  199,  383,  382,  381,
      380,  379,  378,  377,  376,  375,  199,  199,  199,  199,
      199,  199,  115,  374,  115,  373,  115,  372,  116,  371,
      370,  369,  368,  367,  366,  365,  364,  363,  362,  361,
      360,  359,  358,  357,  356,  355,  354,  117,  118,  119,
      120,  250,  250,  250,  250,  250,  250,  250,  353,  352,
      351,  350,  349,  348,  347,  346,  345,  250,  250,  250,

      250,  250,  250,  132,  132,  132,  132,  132,  132,  132,
      344,  343,  342,  341,  117,  118,  119,  120,  340,  132,
      132,  132,  132,  132,  132,  288,  288,  288,  288,  288,
      288,  288,  339,  336,  335,  334,  333,  332,  331,  330,
      329,  288,  288,  288,  288,  288,  288,   50,   50,   50,
       50,   50,   50,   55,   55,  328,  327,   55,   55,   68,
       68,  128,  326,  325,  128,  128,  128,  137,  137,  137,
      137,  137,  137,  324,  323,  322,  321,  320,  319,  318,
      317,  316,  315,  314,  313,  312,  311,  310,  309,  308,
      307,  306,  305,  304,  303,  302,  301,  300,  299,  298,

      297,  296,  295,  294,  293,  292,  291,  290,  289,  287,
      286,  285,  284,  283,  282,  281,  280,  279,  278,  277,
      276,  275,  274,  273,  272,  271,  270,  269,  268,  267,
      266,  265,  264,  263,  262,  261,  260,  259,  258,  257,
      256,  255,  254,  253,  252,  251,  249,  248,  248,  248,
      248,  247,  246,  245,  244,  243,  242,  241,  240,  239,
      238,  237,  236,  235,  234,  233,  232,  231,  230,  229,
      228,  227,  226,  225,  224,  223,  222,  221,  220,  219,
      218,  217,  216,  215,  214,  213,  212,  211,  210,  209,
      208,  207,  206,  205,  202,  138,  197,  197,  197,  197,

      196,  195,  115,  121,  189,  189,  189,  189,  188,  185,
      184,  181,  176,  175,  174,  173,  172,  171,  170,  169,
      166,  165,  164,  163,  162,  161,  160,  159,  158,  157,
      156,  155,  154,  153,  152,  151,  150,  147,  146,  145,
      144,  138,  135,  127,  122,  121,  114,  109,  108,  107,
      101,  100,   95,   89,   74,   73,   72,   69,  406,    5,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,

      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406
    } ;

static yyconst flex_int16_t yy_chk[728] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    2,   10,    2,
       40,    2,   40,    2,    3,    3,    4,    4,    3,    3,
        4,    4,   11,   11,   12,   22,   12,   12,   12,   13,
       10,   22,   13,   14,   18,   14,   14,   23,  412,   18,

       15,   14,   15,   15,   15,   36,   23,   24,   15,   14,
       25,   36,   27,   55,   25,   14,   26,   41,   41,  404,
       25,   24,   15,   27,   24,   26,   30,   29,   29,    2,
        2,    2,    2,   14,   29,   55,   30,   32,   32,   35,
       57,   43,   35,   43,  402,   43,   44,   43,   44,  101,
       44,   32,   44,   32,   35,   47,   51,   47,   48,   48,
       51,   51,   53,   64,   64,  101,   53,   53,   73,   58,
      401,   58,   58,   58,  400,   91,   57,   58,   57,   60,
       60,   60,   63,   63,   63,   60,   73,   91,   63,   65,
      104,   58,   65,   65,   65,  102,  107,  107,  102,   60,

      119,  119,   63,   43,   43,   43,   43,  104,   44,   44,
       44,   44,   67,  398,   67,   67,   67,  112,  112,  112,
       67,  118,  307,  118,  112,  112,  112,  115,  307,  115,
      396,  115,  395,  115,   67,  122,  393,  122,  132,  122,
      392,  122,  125,  125,  125,  141,  141,  141,  129,  125,
      125,  125,  129,  129,  131,  142,  142,  142,  131,  131,
      132,  136,  391,  389,  136,  136,  136,  139,  139,  139,
      388,  140,  387,  139,  140,  140,  140,  193,  193,  193,
      200,  200,  200,  201,  201,  201,  193,  139,  386,  115,
      115,  115,  115,  203,  203,  203,  383,  122,  122,  122,

      122,  133,  204,  204,  204,  382,  381,  380,  133,  133,
      133,  133,  133,  133,  133,  197,  379,  197,  378,  197,
      376,  197,  374,  133,  133,  133,  133,  133,  133,  133,
      134,  134,  134,  134,  134,  134,  134,  372,  370,  367,
      366,  361,  360,  358,  357,  356,  134,  134,  134,  134,
      134,  134,  248,  355,  248,  353,  248,  352,  248,  350,
      349,  348,  347,  346,  344,  343,  342,  341,  339,  338,
      337,  336,  335,  333,  332,  331,  328,  197,  197,  197,
      197,  198,  198,  198,  198,  198,  198,  198,  326,  324,
      323,  322,  321,  320,  319,  318,  317,  198,  198,  198,

      198,  198,  198,  199,  199,  199,  199,  199,  199,  199,
      316,  313,  312,  311,  248,  248,  248,  248,  310,  199,
      199,  199,  199,  199,  199,  250,  250,  250,  250,  250,
      250,  250,  309,  306,  305,  304,  303,  301,  299,  298,
      297,  250,  250,  250,  250,  250,  250,  407,  407,  407,
      407,  407,  407,  408,  408,  296,  295,  408,  408,  409,
      409,  410,  294,  293,  410,  410,  410,  411,  411,  411,
      411,  411,  411,  292,  291,  290,  289,  287,  286,  285,
      284,  283,  282,  280,  279,  278,  277,  276,  275,  273,
      272,  271,  270,  269,  268,  267,  264,  263,  262,  261,

      260,  258,  257,  256,  255,  254,  253,  252,  251,  249,
      246,  245,  244,  242,  241,  240,  239,  238,  237,  236,
      235,  234,  233,  232,  229,  228,  227,  226,  225,  224,
      223,  222,  221,  219,  218,  217,  216,  215,  214,  212,
      211,  210,  209,  208,  206,  205,  196,  195,  194,  192,
      191,  188,  187,  186,  185,  184,  183,  182,  181,  180,
      179,  178,  177,  176,  175,  174,  173,  172,  171,  170,
      169,  168,  167,  166,  165,  164,  163,  162,  161,  160,
      159,  158,  157,  156,  155,  154,  153,  152,  150,  149,
      147,  146,  145,  144,  138,  137,  127,  126,  124,  123,

      121,  120,  117,  116,  114,  113,  111,  110,  108,  106,
      105,  103,  100,   98,   97,   96,   95,   94,   93,   92,
       90,   89,   88,   87,   86,   85,   84,   83,   82,   81,
       80,   79,   78,   77,   76,   75,   74,   72,   71,   70,
       69,   61,   59,   49,   46,   45,   42,   39,   38,   37,
       34,   33,   31,   28,   21,   20,   19,   17,    5,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,

      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[65] =
    {   0,
0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 
    0, 0, 0, 1, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int webidl__flex_debug;
int webidl__flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *webidl_text;
#line 1 "webidl-lexer.l"
#line 2 "webidl-lexer.l"

/* This is a unicode tolerant lexer for web IDL
 *
 * This file is part of nsgenbind.
 * Licensed under the MIT License,
 *                http://www.opensource.org/licenses/mit-license.php
 * Copyright 2012 Vincent Sanders <vince@netsurf-browser.org>
 *
 * Derived from:
 *
 * W3C WEB IDL - http://www.w3.org/TR/WebIDL/ (especially the grammar
 * in apendix A)
 *
 * The ECMA script spec -
 * http://ecma-international.org/ecma-262/5.1/#sec-7.2 (expecially
 * section 7.2 for unicode value handling)
 */

#include <stdbool.h>
#include <stdio.h>
#include <string.h>

#include "webidl-parser.h"

#define YY_USER_ACTION yylloc->first_line = yylloc->last_line; \
    yylloc->first_column = yylloc->last_column + 1; \
    yylloc->last_column += webidl_leng;

/* Ensure compatability with bison 2.6 and later */
#if ! defined YYSTYPE && ! defined YYSTYPE_IS_DECLARED && defined WEBIDL_STYPE_IS_DECLARED
#define YYSTYPE WEBIDL_STYPE
#endif

#if ! defined YYLTYPE && ! defined YYLTYPE_IS_DECLARED && defined WEBIDL_LTYPE_IS_DECLARED
#define YYLTYPE WEBIDL_LTYPE
#endif

/* lexer options */
/* regular definitions */
/* ecmascript section 7.2 defines whitespace http://ecma-international.org/ecma-262/5.1/#sec-7.2
* Web IDL appendix A has the IDL grammar http://www.w3.org/TR/WebIDL/#idl-grammar
*/
/* we do not define space, line feed, carriage return, tab, vertical
*  tab or form feed here as they are the standard C escapes
*/
/* other Unicode “space separator” */
/* Line separator \u2028 */
/* paragraph separator \u2029 */
/* non breaking space \u00A0 */
/* web idl grammar for whitespace matches single and multiline
 *  comments too. Here there are separate definitions for both single
 *  and multiline comments.
 */
/* integer numbers in hexidecimal, decimal and octal, slight extension
 *   to spec which only allows for decimal values 
 */
/* decimal floating point number */ 
/* quoted string. spec simply has "[^"]*" but here escapes are allowed for */
/* web idl identifier direct from spec */
/* web idl other direct from spec */
/* used for #include directive - not part of web idl spec */

#line 859 "webidl-lexer.c"

#define INITIAL 0
#define incl 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int webidl_lex_destroy (void );

int webidl_get_debug (void );

void webidl_set_debug (int debug_flag  );

YY_EXTRA_TYPE webidl_get_extra (void );

void webidl_set_extra (YY_EXTRA_TYPE user_defined  );

FILE *webidl_get_in (void );

void webidl_set_in  (FILE * _in_str  );

FILE *webidl_get_out (void );

void webidl_set_out  (FILE * _out_str  );

			int webidl_get_leng (void );

char *webidl_get_text (void );

int webidl_get_lineno (void );

void webidl_set_lineno (int _line_number  );

YYSTYPE * webidl_get_lval (void );

void webidl_set_lval (YYSTYPE * yylval_param  );

       YYLTYPE *webidl_get_lloc (void );
    
        void webidl_set_lloc (YYLTYPE * yylloc_param  );
    
/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int webidl_wrap (void );
#else
extern int webidl_wrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( webidl_text, (size_t) webidl_leng, 1, webidl_out )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( webidl_in )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( webidl_in ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, webidl_in)) == 0 && ferror(webidl_in)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(webidl_in); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int webidl_lex \
               (YYSTYPE * yylval_param,YYLTYPE * yylloc_param );

#define YY_DECL int webidl_lex \
               (YYSTYPE * yylval_param, YYLTYPE * yylloc_param )
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after webidl_text and webidl_leng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( webidl_leng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(webidl_text[webidl_leng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
        YYSTYPE * yylval;
    
        YYLTYPE * yylloc;
    
    yylval = yylval_param;

    yylloc = yylloc_param;

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! webidl_in )
			webidl_in = stdin;

		if ( ! webidl_out )
			webidl_out = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			webidl_ensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				webidl__create_buffer(webidl_in,YY_BUF_SIZE );
		}

		webidl__load_buffer_state( );
		}

	{
#line 114 "webidl-lexer.l"


#line 1100 "webidl-lexer.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of webidl_text. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 407 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 406 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < webidl_leng; ++yyl )
				if ( webidl_text[yyl] == '\n' )
					   
    webidl_lineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 116 "webidl-lexer.l"
++yylloc->last_column; /* skip whitespace */
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 118 "webidl-lexer.l"
if (webidl_text[0] != '\r') {
                        /* update position counts */
                        ++yylloc->last_line;
                        yylloc->last_column = 0;
                    }
	YY_BREAK
/* Simple text terminals */
case 3:
YY_RULE_SETUP
#line 126 "webidl-lexer.l"
return TOK_BOOLEAN;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 128 "webidl-lexer.l"
return TOK_BYTE;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 130 "webidl-lexer.l"
return TOK_OCTET; 
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 132 "webidl-lexer.l"
return TOK_ATTRIBUTE;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 134 "webidl-lexer.l"
return TOK_CALLBACK;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 136 "webidl-lexer.l"
return TOK_CONST;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 138 "webidl-lexer.l"
return TOK_CREATOR;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 140 "webidl-lexer.l"
return TOK_DELETER;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 142 "webidl-lexer.l"
return TOK_DICTIONARY;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 144 "webidl-lexer.l"
return TOK_ENUM;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 146 "webidl-lexer.l"
return TOK_EXCEPTION;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 148 "webidl-lexer.l"
return TOK_GETTER;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 150 "webidl-lexer.l"
return TOK_IMPLEMENTS;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 152 "webidl-lexer.l"
return TOK_INHERIT;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 154 "webidl-lexer.l"
return TOK_INTERFACE;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 156 "webidl-lexer.l"
return TOK_LEGACYCALLER;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 158 "webidl-lexer.l"
return TOK_PARTIAL;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 160 "webidl-lexer.l"
return TOK_SETTER;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 162 "webidl-lexer.l"
return TOK_STATIC;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 164 "webidl-lexer.l"
return TOK_STRINGIFIER;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 166 "webidl-lexer.l"
return TOK_TYPEDEF;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 168 "webidl-lexer.l"
return TOK_UNRESTRICTED;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 170 "webidl-lexer.l"
return TOK_ELLIPSIS;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 172 "webidl-lexer.l"
return TOK_DATE;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 174 "webidl-lexer.l"
return TOK_STRING; /* dom strings are just strings */
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 176 "webidl-lexer.l"
return TOK_INFINITY;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 178 "webidl-lexer.l"
return TOK_NAN;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 180 "webidl-lexer.l"
return TOK_ANY;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 182 "webidl-lexer.l"
return TOK_DOUBLE;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 184 "webidl-lexer.l"
return TOK_FALSE;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 186 "webidl-lexer.l"
return TOK_FLOAT;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 188 "webidl-lexer.l"
return TOK_LONG;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 190 "webidl-lexer.l"
return TOK_NULL_LITERAL;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 192 "webidl-lexer.l"
yylval->text = strdup(webidl_text); return TOK_IDENTIFIER;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 194 "webidl-lexer.l"
return TOK_OR;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 196 "webidl-lexer.l"
return TOK_OPTIONAL;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 198 "webidl-lexer.l"
return TOK_SEQUENCE;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 200 "webidl-lexer.l"
return TOK_SHORT;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 202 "webidl-lexer.l"
return TOK_TRUE;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 204 "webidl-lexer.l"
return TOK_UNSIGNED;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 206 "webidl-lexer.l"
return TOK_VOID;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 208 "webidl-lexer.l"
return TOK_READONLY;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 210 "webidl-lexer.l"
return TOK_PROMISE;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 212 "webidl-lexer.l"
return TOK_ITERABLE;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 214 "webidl-lexer.l"
return TOK_LEGACYITERABLE;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 216 "webidl-lexer.l"
return TOK_REQUIRED;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 218 "webidl-lexer.l"
return TOK_CONSTRUCTOR;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 220 "webidl-lexer.l"
return TOK_NAMEDCONSTRUCTOR;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 222 "webidl-lexer.l"
{
                        /* A leading "_" is used to escape an identifier from 
                         *   looking like a reserved word terminal. */
                        yylval->text = (webidl_text[0] == '_') ? strdup(webidl_text + 1) : strdup(webidl_text);
                        return TOK_IDENTIFIER;
                    }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 229 "webidl-lexer.l"
yylval->value = strtol(webidl_text, NULL, 10); return TOK_INT_LITERAL;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 231 "webidl-lexer.l"
yylval->value = strtol(webidl_text, NULL, 8); return TOK_INT_LITERAL;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 233 "webidl-lexer.l"
yylval->value = strtol(webidl_text, NULL, 16); return TOK_INT_LITERAL;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 235 "webidl-lexer.l"
yylval->text = strdup(webidl_text); return TOK_FLOAT_LITERAL;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 237 "webidl-lexer.l"
yylval->text = strdup(webidl_text + 1); *(yylval->text + webidl_leng - 2) = 0; return TOK_STRING_LITERAL;
	YY_BREAK
case 57:
/* rule 57 can match eol */
YY_RULE_SETUP
#line 239 "webidl-lexer.l"
{
                        /* multicomment */
                        char* s = webidl_text;
                        for (; *s; ++s)
                        {
                            if (*s == '\n')
                            {
                                ++yylloc->last_line;
                                yylloc->last_column = 0;
                            }
                            else
                            {
                                ++yylloc->last_column;
                            }
                        }
                        if (strncmp(webidl_text, "/**", 3) == 0)
                        {
                            /* Javadoc style comment */
                            yylval->text = strdup(webidl_text);
                            return TOK_JAVADOC;
                        }
                    }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 262 "webidl-lexer.l"
{
                        /* singlecomment */
                        int c;

                        do {
                            c = input();
                        } while (c != '\n' && c != '\r' && c != EOF);
                        ++yylloc->last_line;
                        yylloc->last_column = 0;
                    }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 275 "webidl-lexer.l"
BEGIN(incl);
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 277 "webidl-lexer.l"
return (int) webidl_text[0];
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 279 "webidl-lexer.l"
/* eat the whitespace and open quotes */
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 281 "webidl-lexer.l"
{ 
                        /* got the include file name */
                        webidl_in = fopen( webidl_text, "r" );
     
                        if ( ! webidl_in ) {
                            fprintf(stderr, "Unable to open include %s\n", webidl_text);
                            exit(3);
                        }
     			webidl_push_buffer_state(webidl__create_buffer(webidl_in,YY_BUF_SIZE ));
     
                        BEGIN(INITIAL);
                    }
	YY_BREAK
case 63:
/* rule 63 can match eol */
YY_RULE_SETUP
#line 294 "webidl-lexer.l"
BEGIN(INITIAL);
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(incl):
#line 296 "webidl-lexer.l"
{
     			webidl_pop_buffer_state();
     
                        if ( !YY_CURRENT_BUFFER ) {
                            yyterminate();
                        } else {
                            BEGIN(incl);
                        }

                    }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 308 "webidl-lexer.l"
ECHO;
	YY_BREAK
#line 1552 "webidl-lexer.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed webidl_in at a new source and called
			 * webidl_lex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = webidl_in;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( webidl_wrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * webidl_text, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of webidl_lex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					webidl_realloc((void *) b->yy_ch_buf,(yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			webidl_restart(webidl_in  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) webidl_realloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,(yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 407 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 407 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 406);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					webidl_restart(webidl_in );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( webidl_wrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve webidl_text */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');
	if ( YY_CURRENT_BUFFER_LVALUE->yy_at_bol )
		   
    webidl_lineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void webidl_restart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        webidl_ensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            webidl__create_buffer(webidl_in,YY_BUF_SIZE );
	}

	webidl__init_buffer(YY_CURRENT_BUFFER,input_file );
	webidl__load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void webidl__switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		webidl_pop_buffer_state();
	 *		webidl_push_buffer_state(new_buffer);
     */
	webidl_ensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	webidl__load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (webidl_wrap()) processing, but the only time this flag
	 * is looked at is after webidl_wrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void webidl__load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	webidl_in = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE webidl__create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) webidl_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in webidl__create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) webidl_alloc((yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in webidl__create_buffer()" );

	b->yy_is_our_buffer = 1;

	webidl__init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with webidl__create_buffer()
 * 
 */
    void webidl__delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		webidl_free((void *) b->yy_ch_buf  );

	webidl_free((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a webidl_restart() or at EOF.
 */
    static void webidl__init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	webidl__flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then webidl__init_buffer was _probably_
     * called from webidl_restart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void webidl__flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		webidl__load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void webidl_push_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	webidl_ensure_buffer_stack();

	/* This block is copied from webidl__switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from webidl__switch_to_buffer. */
	webidl__load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void webidl_pop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	webidl__delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		webidl__load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void webidl_ensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)webidl_alloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in webidl_ensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)webidl_realloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in webidl_ensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE webidl__scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) webidl_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in webidl__scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	webidl__switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to webidl_lex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       webidl__scan_bytes() instead.
 */
YY_BUFFER_STATE webidl__scan_string (yyconst char * yystr )
{
    
	return webidl__scan_bytes(yystr,(int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to webidl_lex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE webidl__scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) webidl_alloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in webidl__scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = webidl__scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in webidl__scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up webidl_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		webidl_text[webidl_leng] = (yy_hold_char); \
		(yy_c_buf_p) = webidl_text + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		webidl_leng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int webidl_get_lineno  (void)
{
        
    return webidl_lineno;
}

/** Get the input stream.
 * 
 */
FILE *webidl_get_in  (void)
{
        return webidl_in;
}

/** Get the output stream.
 * 
 */
FILE *webidl_get_out  (void)
{
        return webidl_out;
}

/** Get the length of the current token.
 * 
 */
int webidl_get_leng  (void)
{
        return webidl_leng;
}

/** Get the current token.
 * 
 */

char *webidl_get_text  (void)
{
        return webidl_text;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void webidl_set_lineno (int  _line_number )
{
    
    webidl_lineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see webidl__switch_to_buffer
 */
void webidl_set_in (FILE *  _in_str )
{
        webidl_in = _in_str ;
}

void webidl_set_out (FILE *  _out_str )
{
        webidl_out = _out_str ;
}

int webidl_get_debug  (void)
{
        return webidl__flex_debug;
}

void webidl_set_debug (int  _bdebug )
{
        webidl__flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from webidl_lex_destroy(), so don't allocate here.
     */

    /* We do not touch webidl_lineno unless the option is enabled. */
    webidl_lineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    webidl_in = stdin;
    webidl_out = stdout;
#else
    webidl_in = NULL;
    webidl_out = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * webidl_lex_init()
     */
    return 0;
}

/* webidl_lex_destroy is for both reentrant and non-reentrant scanners. */
int webidl_lex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		webidl__delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		webidl_pop_buffer_state();
	}

	/* Destroy the stack itself. */
	webidl_free((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * webidl_lex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *webidl_alloc (yy_size_t  size )
{
			return malloc(size);
}

void *webidl_realloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void webidl_free (void * ptr )
{
			free( (char *) ptr );	/* see webidl_realloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 308 "webidl-lexer.l"



