#define PACKAGE_NAME "dosfstools"
#define PACKAGE_TARNAME "dosfstools"
#define PACKAGE_VERSION "4.1"
#define PACKAGE_STRING "dosfstools 4.1"
#define PACKAGE_BUGREPORT ""
#define PACKAGE_URL ""
#define PACKAGE "dosfstools"
#define VERSION "4.1"
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define HAVE_ERR_H 1
#define HAVE_LINUX_FD_H 1
#define HAVE_LINUX_HDREG_H 1
#define HAVE_LINUX_VERSION_H 1
#define HAVE_ENDIAN_H 1
#define HAVE_DECL_GETMNTENT 1
#define HAVE_DECL_GETMNTINFO 0
