#define PACKAGE_DATA_DIR "/share"
#define WITH_INOTIFY 1

#define PACKAGE_NAME "transmission"
#define PACKAGE_TARNAME "transmission"
#define PACKAGE_VERSION "2.94"
#define PACKAGE_STRING "transmission 2.94"
#define PACKAGE_BUGREPORT "https://github.com/transmission/transmission"
#define PACKAGE_URL ""
#define PACKAGE "transmission"
#define VERSION "2.94"
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define HAVE_DLFCN_H 1
#define LT_OBJDIR ".libs/"
#define STDC_HEADERS 1
#define TIME_WITH_SYS_TIME 1
#define HAVE_STDBOOL_H 1
#define HAVE_ICONV 1
#define HAVE_PREAD 1
#define HAVE_PWRITE 1
#define HAVE_LRINTF 1
#define HAVE_STRLCPY 1
#define HAVE_DAEMON 1
#define HAVE_DIRNAME 1
#define HAVE_BASENAME 1
#define HAVE_STRCASECMP 1
#define HAVE_LOCALTIME_R 1
#define HAVE_FALLOCATE64 1
#define HAVE_POSIX_FALLOCATE 1
#define HAVE_MEMMEM 1
#define HAVE_STRSEP 1
#define HAVE_STRTOLD 1
#define HAVE_SYSLOG 1
#define HAVE_VALLOC 1
#define HAVE_GETPAGESIZE 1
#define HAVE_POSIX_MEMALIGN 1
#define HAVE_STATVFS 1
#define HAVE_MKDTEMP 1
#define HAVE_USELOCALE 1
#define HAVE_PTHREAD 1
#define HAVE_GETMNTENT 1
#define HAVE_DECL_POSIX_FADVISE 1
#define HAVE_POSIX_FADVISE 1
#define HAVE_SYS_STATVFS_H 1
#define WITH_UTP 1
