/* #undef ENABLE_NLS */
/* #undef HAVE_1ARG_ASSIGN_STR */
/* #undef HAVE_1ARG_LOOKUP_BDEV */
/* #undef HAVE_ACCESS_OK_TYPE */
/* #undef HAVE_ADD_DISK_RET */
/* #undef HAVE_AES */
#define HAVE_AIO_H 1
/* #undef HAVE_AVX */
/* #undef HAVE_AVX2 */
/* #undef HAVE_AVX512BW */
/* #undef HAVE_AVX512CD */
/* #undef HAVE_AVX512DQ */
/* #undef HAVE_AVX512ER */
/* #undef HAVE_AVX512F */
/* #undef HAVE_AVX512IFMA */
/* #undef HAVE_AVX512PF */
/* #undef HAVE_AVX512VBMI */
/* #undef HAVE_AVX512VL */
/* #undef HAVE_BACKTRACE */
/* #undef HAVE_BDEVNAME */
/* #undef HAVE_BDEV_CHECK_MEDIA_CHANGE */
/* #undef HAVE_BDEV_FILE_OPEN_BY_PATH */
/* #undef HAVE_BDEV_IO_ACCT_63 */
/* #undef HAVE_BDEV_IO_ACCT_OLD */
/* #undef HAVE_BDEV_KOBJ */
/* #undef HAVE_BDEV_MAX_DISCARD_SECTORS */
/* #undef HAVE_BDEV_MAX_SECURE_ERASE_SECTORS */
/* #undef HAVE_BDEV_NR_BYTES */
/* #undef HAVE_BDEV_OPEN_BY_PATH */
/* #undef HAVE_BDEV_RELEASE */
/* #undef HAVE_BDEV_SUBMIT_BIO_RETURNS_VOID */
/* #undef HAVE_BDEV_WHOLE */
/* #undef HAVE_BIO_ALLOC_4ARG */
/* #undef HAVE_BIO_BDEV_DISK */
/* #undef HAVE_BIO_IO_ACCT */
/* #undef HAVE_BIO_MAX_SEGS */
/* #undef HAVE_BIO_SET_DEV_GPL_ONLY */
/* #undef HAVE_BIO_SET_DEV_MACRO */
/* #undef HAVE_BIO_SET_OP_ATTRS */
/* #undef HAVE_BLKDEV_GET_BY_PATH_4ARG */
/* #undef HAVE_BLKDEV_GET_ERESTARTSYS */
/* #undef HAVE_BLKDEV_ISSUE_DISCARD_ASYNC_FLAGS */
/* #undef HAVE_BLKDEV_ISSUE_DISCARD_ASYNC_NOFLAGS */
/* #undef HAVE_BLKDEV_ISSUE_DISCARD_FLAGS */
/* #undef HAVE_BLKDEV_ISSUE_DISCARD_NOFLAGS */
/* #undef HAVE_BLKDEV_ISSUE_SECURE_ERASE */
/* #undef HAVE_BLKDEV_PUT */
/* #undef HAVE_BLKDEV_PUT_HOLDER */
/* #undef HAVE_BLKDEV_QUEUE_LIMITS_FEATURES */
/* #undef HAVE_BLKDEV_REREAD_PART */
/* #undef HAVE_BLKG_TRYGET */
/* #undef HAVE_BLKG_TRYGET_GPL_ONLY */
/* #undef HAVE_BLK_ALLOC_DISK */
/* #undef HAVE_BLK_ALLOC_DISK_2ARG */
/* #undef HAVE_BLK_ALLOC_QUEUE_REQUEST_FN */
/* #undef HAVE_BLK_ALLOC_QUEUE_REQUEST_FN_RH */
/* #undef HAVE_BLK_CLEANUP_DISK */
/* #undef HAVE_BLK_MODE_T */
/* #undef HAVE_BLK_MQ_RQ_HCTX */
/* #undef HAVE_BLK_QUEUE_BDI_DYNAMIC */
/* #undef HAVE_BLK_QUEUE_DISCARD */
/* #undef HAVE_BLK_QUEUE_DISK_BDI */
/* #undef HAVE_BLK_QUEUE_SECURE_ERASE */
/* #undef HAVE_BLK_QUEUE_UPDATE_READAHEAD */
/* #undef HAVE_BLK_STS_RESV_CONFLICT */
/* #undef HAVE_BLOCK_DEVICE_OPERATIONS_RELEASE_1ARG */
/* #undef HAVE_BLOCK_DEVICE_OPERATIONS_REVALIDATE_DISK */
/* #undef HAVE_CHECK_DISK_CHANGE */
/* #undef HAVE_COPY_SPLICE_READ */
/* #undef HAVE_CPU_HAS_FEATURE_GPL_ONLY */
/* #undef HAVE_DCGETTEXT */
/* #undef HAVE_DECLARE_EVENT_CLASS */
/* #undef HAVE_DEQUEUE_SIGNAL_3ARG_TYPE */
/* #undef HAVE_DEQUEUE_SIGNAL_4ARG */
/* #undef HAVE_DEVT_LOOKUP_BDEV */
/* #undef HAVE_DISK_CHECK_MEDIA_CHANGE */
/* #undef HAVE_DISK_IO_ACCT */
/* #undef HAVE_DISK_UPDATE_READAHEAD */
#define HAVE_DLFCN_H 1
#define HAVE_EXECVPE 1
/* #undef HAVE_FAULT_IN_IOV_ITER_READABLE */
/* #undef HAVE_FILE_F_VERSION */
/* #undef HAVE_FLUSH_DCACHE_PAGE_GPL_ONLY */
#define HAVE_FORMAT_OVERFLOW 1
/* #undef HAVE_FSYNC_BDEV */
/* #undef HAVE_GENERIC_FADVISE */
/* #undef HAVE_GENERIC_FILLATTR_IDMAP */
/* #undef HAVE_GENERIC_FILLATTR_IDMAP_REQMASK */
/* #undef HAVE_GENERIC_FILLATTR_USERNS */
/* #undef HAVE_GENERIC_IO_ACCT_4ARG */
/* #undef HAVE_GENHD_FL_EXT_DEVT */
/* #undef HAVE_GENHD_FL_NO_PART */
/* #undef HAVE_GETTEXT */
#define HAVE_GETTID 1
/* #undef HAVE_GET_ACL */
/* #undef HAVE_GET_ACL_RCU */
/* #undef HAVE_GET_INODE_ACL */
/* #undef HAVE_IATTR_VFSID */
/* #undef HAVE_ICONV */
/* #undef HAVE_IDMAP_IOPS_GETATTR */
/* #undef HAVE_IDMAP_IOPS_SETATTR */
/* #undef HAVE_IDMAP_MNT_API */
/* #undef HAVE_IDMAP_NO_USERNS */
#define HAVE_IMPLICIT_FALLTHROUGH 1
#define HAVE_INFINITE_RECURSION 1
/* #undef HAVE_INODE_GET_ATIME */
/* #undef HAVE_INODE_GET_CTIME */
/* #undef HAVE_INODE_GET_MTIME */
/* #undef HAVE_INODE_OWNER_OR_CAPABLE */
/* #undef HAVE_INODE_OWNER_OR_CAPABLE_IDMAP */
/* #undef HAVE_INODE_OWNER_OR_CAPABLE_USERNS */
/* #undef HAVE_INODE_SET_ATIME_TO_TS */
/* #undef HAVE_INODE_SET_CTIME_TO_TS */
/* #undef HAVE_INODE_SET_MTIME_TO_TS */
/* #undef HAVE_INODE_TIMESTAMP_TRUNCATE */
#define HAVE_INTTYPES_H 1
/* #undef HAVE_IOPS_CREATE_IDMAP */
/* #undef HAVE_IOPS_CREATE_USERNS */
/* #undef HAVE_IOPS_MKDIR_IDMAP */
/* #undef HAVE_IOPS_MKDIR_USERNS */
/* #undef HAVE_IOPS_MKNOD_IDMAP */
/* #undef HAVE_IOPS_MKNOD_USERNS */
/* #undef HAVE_IOPS_PERMISSION_IDMAP */
/* #undef HAVE_IOPS_PERMISSION_USERNS */
/* #undef HAVE_IOPS_RENAME_IDMAP */
/* #undef HAVE_IOPS_RENAME_USERNS */
/* #undef HAVE_IOPS_SYMLINK_IDMAP */
/* #undef HAVE_IOPS_SYMLINK_USERNS */
/* #undef HAVE_IOV_ITER_TYPE */
#define HAVE_ISSETUGID 1
/* #undef HAVE_ITER_IOV */
/* #undef HAVE_ITER_IS_UBUF */
/* #undef HAVE_KERNEL_FPU */
/* #undef HAVE_KERNEL_FPU_API_HEADER */
/* #undef HAVE_KERNEL_FPU_INTERNAL */
/* #undef HAVE_KERNEL_FPU_INTERNAL_HEADER */
#define HAVE_KERNEL_INFINITE_RECURSION 1
/* #undef HAVE_KERNEL_INTPTR_T */
/* #undef HAVE_KERNEL_NEON */
/* #undef HAVE_KERNEL_OBJTOOL */
/* #undef HAVE_KERNEL_OBJTOOL_HEADER */
/* #undef HAVE_KERNEL_STRLCPY */
/* #undef HAVE_KMAP_LOCAL_PAGE */
/* #undef HAVE_LIBAIO */
#define HAVE_LIBBLKID 1
/* #undef HAVE_LIBCRYPTO */
#define HAVE_LIBTIRPC 1
/* #undef HAVE_LIBUDEV */
/* #undef HAVE_LIBUNWIND */
/* #undef HAVE_LIBUNWIND_ELF */
#define HAVE_LIBUUID 1
/* #undef HAVE_LINUX_EXPERIMENTAL */
/* #undef HAVE_MAKEDEV_IN_MKDEV */
#define HAVE_MAKEDEV_IN_SYSMACROS 1
/* #undef HAVE_MAKE_REQUEST_FN_RET_QC */
#define HAVE_MLOCKALL 1
/* #undef HAVE_MM_PAGE_FLAG_ERROR */
/* #undef HAVE_MM_PAGE_MAPPING */
/* #undef HAVE_MM_PAGE_SIZE */
#define HAVE_MOVBE 1
/* #undef HAVE_PAGEMAP_FOLIO_WAIT_BIT */
/* #undef HAVE_PART_TO_DEV */
/* #undef HAVE_PATH_IOPS_GETATTR */
#define HAVE_PCLMULQDQ 1
/* #undef HAVE_PIN_USER_PAGES_UNLOCKED */
/* #undef HAVE_PROC_HANDLER_CTL_TABLE_CONST */
/* #undef HAVE_PROC_OPS_STRUCT */
/* #undef HAVE_PYTHON */
/* #undef HAVE_QAT */
/* #undef HAVE_RECLAIM_STATE_RECLAIMED */
/* #undef HAVE_REGISTER_SHRINKER_VARARG */
/* #undef HAVE_REGISTER_SYSCTL_SZ */
/* #undef HAVE_REGISTER_SYSCTL_TABLE */
/* #undef HAVE_RENAME_WANTS_FLAGS */
/* #undef HAVE_REVALIDATE_DISK */
/* #undef HAVE_REVALIDATE_DISK_SIZE */
/* #undef HAVE_SECURITY_PAM_MODULES_H */
/* #undef HAVE_SETATTR_PREPARE_IDMAP */
/* #undef HAVE_SETATTR_PREPARE_NO_USERNS */
/* #undef HAVE_SETATTR_PREPARE_USERNS */
/* #undef HAVE_SET_ACL_IDMAP_DENTRY */
/* #undef HAVE_SET_ACL_USERNS */
/* #undef HAVE_SET_ACL_USERNS_DENTRY_ARG2 */
/* #undef HAVE_SHRINKER_REGISTER */
/* #undef HAVE_SIGINFO */
/* #undef HAVE_SSE */
/* #undef HAVE_SSE2 */
/* #undef HAVE_SSE3 */
/* #undef HAVE_SSE4_1 */
/* #undef HAVE_SSE4_2 */
/* #undef HAVE_SSSE3 */
/* #undef HAVE_STACK_FRAME_NON_STANDARD */
/* #undef HAVE_STANDALONE_LINUX_STDARG */
#define HAVE_STDINT_H 1
#define HAVE_STDIO_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRINGS_H 1
#define HAVE_STRING_H 1
#define HAVE_STRLCAT 1
#define HAVE_STRLCPY 1
/* #undef HAVE_SUBMIT_BIO_IN_BLOCK_DEVICE_OPERATIONS */
/* #undef HAVE_SUPER_BLOCK_S_SHRINK */
/* #undef HAVE_SUPER_BLOCK_S_SHRINK_PTR */
/* #undef HAVE_SYNC_BLOCKDEV */
/* #undef HAVE_SYSFS_DEFAULT_GROUPS */
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TYPES_H 1
/* #undef HAVE_TMPFILE_DENTRY */
/* #undef HAVE_TMPFILE_IDMAP */
/* #undef HAVE_TMPFILE_USERNS */
/* #undef HAVE_TOTALHIGH_PAGES */
/* #undef HAVE_TOTALRAM_PAGES_FUNC */
/* #undef HAVE_UDEV_DEVICE_GET_IS_INITIALIZED */
/* #undef HAVE_UNDERSCORE_KERNEL_FPU */
#define HAVE_UNISTD_H 1
/* #undef HAVE_USERNS_IOPS_GETATTR */
/* #undef HAVE_USERNS_IOPS_SETATTR */
/* #undef HAVE_VFS_CLONE_FILE_RANGE */
/* #undef HAVE_VFS_DEDUPE_FILE_RANGE */
/* #undef HAVE_VFS_FILEMAP_DIRTY_FOLIO */
/* #undef HAVE_VFS_GENERIC_COPY_FILE_RANGE */
/* #undef HAVE_VFS_MIGRATE_FOLIO */
/* #undef HAVE_VFS_READPAGES */
/* #undef HAVE_VFS_READ_FOLIO */
/* #undef HAVE_VFS_REMAP_FILE_RANGE */
/* #undef HAVE_VFS_SET_PAGE_DIRTY_NOBUFFERS */
/* #undef HAVE_VFS_SPLICE_COPY_FILE_RANGE */
/* #undef HAVE_VMALLOC_PAGE_KERNEL */
/* #undef HAVE_WRITEPAGE_T_FOLIO */
/* #undef HAVE_XATTR_GET_DENTRY_INODE_FLAGS */
/* #undef HAVE_XATTR_SET_DENTRY_INODE */
/* #undef HAVE_XATTR_SET_IDMAP */
/* #undef HAVE_XATTR_SET_USERNS */
#define HAVE_XSAVE 1
#define HAVE_XSAVEOPT 1
#define HAVE_XSAVES 1
/* #undef HAVE_ZERO_PAGE_GPL_ONLY */
#define HAVE_ZLIB 1
/* #undef KERNEL_EXPORTS_X86_FPU */
#define LIBFETCH_DYNAMIC 0
#define LIBFETCH_IS_FETCH 0
#define LIBFETCH_IS_LIBCURL 0
#define LIBFETCH_SONAME ""
#define LT_OBJDIR ".libs/"
/* #undef MAKE_REQUEST_FN_RET */
/* #undef SPL_KTHREAD_COMPLETE_AND_EXIT */
#define SPL_META_ALIAS ZFS_META_ALIAS
#define SPL_META_RELEASE ZFS_META_RELEASE
#define SPL_META_VERSION ZFS_META_VERSION
/* #undef SPL_PDE_DATA */
/* #undef SYSTEM_FREEBSD */
#define SYSTEM_LINUX 1
/* #undef ZFS_DEBUG */
/* #undef ZFS_DEVICE_MINOR */
#define ZFS_META_ALIAS "zfs-2.3.0-1"
#define ZFS_META_AUTHOR "OpenZFS"
/* #undef ZFS_META_DATA */
#define ZFS_META_KVER_MAX "6.12"
#define ZFS_META_KVER_MIN "4.18"
#define ZFS_META_LICENSE "CDDL"
/* #undef ZFS_META_LT_AGE */
/* #undef ZFS_META_LT_CURRENT */
/* #undef ZFS_META_LT_REVISION */
#define ZFS_META_NAME "zfs"
#define ZFS_META_RELEASE "1"
#define ZFS_META_VERSION "2.3.0"
/* #undef ZFS_PERCPU_REF_COUNT_IN_DATA */

#define ZFSEXECDIR "/libexec/zfs"
#define RUNSTATEDIR "/run"
#define SBINDIR "/bin"
#define SYSCONFDIR "/etc"
#define PKGDATADIR "/share/zfs"
#define TEXT_DOMAIN "zfs-linux-user"
