/* #undef ENABLE_NLS */
/* #undef HAVE_1ARG_BIO_END_IO_T */
/* #undef HAVE_1ARG_LOOKUP_BDEV */
/* #undef HAVE_1ARG_SUBMIT_BIO */
/* #undef HAVE_2ARGS_BDI_SETUP_AND_REGISTER */
/* #undef HAVE_2ARGS_VFS_GETATTR */
/* #undef HAVE_2ARGS_ZLIB_DEFLATE_WORKSPACESIZE */
/* #undef HAVE_3ARGS_BDI_SETUP_AND_REGISTER */
/* #undef HAVE_3ARGS_VFS_GETATTR */
/* #undef HAVE_4ARGS_VFS_GETATTR */
/* #undef HAVE_ACCESS_OK_TYPE */
/* #undef HAVE_ACL_REFCOUNT */
/* #undef HAVE_ADD_DISK_RET */
/* #undef HAVE_AES */
#define HAVE_AIO_H 1
/* #undef HAVE_AVX */
/* #undef HAVE_AVX2 */
/* #undef HAVE_AVX512BW */
/* #undef HAVE_AVX512CD */
/* #undef HAVE_AVX512DQ */
/* #undef HAVE_AVX512ER */
/* #undef HAVE_AVX512F */
/* #undef HAVE_AVX512IFMA */
/* #undef HAVE_AVX512PF */
/* #undef HAVE_AVX512VBMI */
/* #undef HAVE_AVX512VL */
/* #undef HAVE_BDEVNAME */
/* #undef HAVE_BDEV_CHECK_MEDIA_CHANGE */
/* #undef HAVE_BDEV_IO_ACCT_63 */
/* #undef HAVE_BDEV_IO_ACCT_OLD */
/* #undef HAVE_BDEV_KOBJ */
/* #undef HAVE_BDEV_MAX_DISCARD_SECTORS */
/* #undef HAVE_BDEV_MAX_SECURE_ERASE_SECTORS */
/* #undef HAVE_BDEV_OPEN_BY_PATH */
/* #undef HAVE_BDEV_RELEASE */
/* #undef HAVE_BDEV_SUBMIT_BIO_RETURNS_VOID */
/* #undef HAVE_BDEV_WHOLE */
/* #undef HAVE_BIO_ALLOC_4ARG */
/* #undef HAVE_BIO_BDEV_DISK */
/* #undef HAVE_BIO_BI_OPF */
/* #undef HAVE_BIO_BI_STATUS */
/* #undef HAVE_BIO_BVEC_ITER */
/* #undef HAVE_BIO_IO_ACCT */
/* #undef HAVE_BIO_MAX_SEGS */
/* #undef HAVE_BIO_SET_DEV */
/* #undef HAVE_BIO_SET_DEV_GPL_ONLY */
/* #undef HAVE_BIO_SET_DEV_MACRO */
/* #undef HAVE_BIO_SET_OP_ATTRS */
/* #undef HAVE_BLKDEV_GET_BY_PATH_4ARG */
/* #undef HAVE_BLKDEV_GET_ERESTARTSYS */
/* #undef HAVE_BLKDEV_ISSUE_DISCARD */
/* #undef HAVE_BLKDEV_ISSUE_DISCARD_ASYNC */
/* #undef HAVE_BLKDEV_ISSUE_SECURE_ERASE */
/* #undef HAVE_BLKDEV_PUT_HOLDER */
/* #undef HAVE_BLKDEV_REREAD_PART */
/* #undef HAVE_BLKG_TRYGET */
/* #undef HAVE_BLKG_TRYGET_GPL_ONLY */
/* #undef HAVE_BLK_ALLOC_DISK */
/* #undef HAVE_BLK_ALLOC_QUEUE_REQUEST_FN */
/* #undef HAVE_BLK_ALLOC_QUEUE_REQUEST_FN_RH */
/* #undef HAVE_BLK_CLEANUP_DISK */
/* #undef HAVE_BLK_MODE_T */
/* #undef HAVE_BLK_MQ */
/* #undef HAVE_BLK_QUEUE_BDI_DYNAMIC */
/* #undef HAVE_BLK_QUEUE_DISCARD */
/* #undef HAVE_BLK_QUEUE_FLAG_CLEAR */
/* #undef HAVE_BLK_QUEUE_FLAG_SET */
/* #undef HAVE_BLK_QUEUE_FLUSH */
/* #undef HAVE_BLK_QUEUE_FLUSH_GPL_ONLY */
/* #undef HAVE_BLK_QUEUE_SECDISCARD */
/* #undef HAVE_BLK_QUEUE_SECURE_ERASE */
/* #undef HAVE_BLK_QUEUE_UPDATE_READAHEAD */
/* #undef HAVE_BLK_QUEUE_WRITE_CACHE */
/* #undef HAVE_BLK_QUEUE_WRITE_CACHE_GPL_ONLY */
/* #undef HAVE_BLK_STS_RESV_CONFLICT */
/* #undef HAVE_BLOCK_DEVICE_OPERATIONS_RELEASE_1ARG */
/* #undef HAVE_BLOCK_DEVICE_OPERATIONS_REVALIDATE_DISK */
/* #undef HAVE_CFLOCALECOPYCURRENT */
/* #undef HAVE_CFLOCALECOPYPREFERREDLANGUAGES */
/* #undef HAVE_CFPREFERENCESCOPYAPPVALUE */
/* #undef HAVE_CHECK_DISK_CHANGE */
/* #undef HAVE_CLEAR_INODE */
/* #undef HAVE_CONST_DENTRY_OPERATIONS */
/* #undef HAVE_COPY_FROM_ITER */
/* #undef HAVE_COPY_SPLICE_READ */
/* #undef HAVE_COPY_TO_ITER */
/* #undef HAVE_CPU_HAS_FEATURE_GPL_ONLY */
/* #undef HAVE_CPU_HOTPLUG */
/* #undef HAVE_CURRENT_TIME */
/* #undef HAVE_DCGETTEXT */
/* #undef HAVE_DECLARE_EVENT_CLASS */
/* #undef HAVE_DENTRY_D_U_ALIASES */
/* #undef HAVE_DEQUEUE_SIGNAL_4ARG */
/* #undef HAVE_DEVT_LOOKUP_BDEV */
/* #undef HAVE_DIRTY_INODE_WITH_FLAGS */
/* #undef HAVE_DISK_CHECK_MEDIA_CHANGE */
/* #undef HAVE_DISK_IO_ACCT */
/* #undef HAVE_DISK_UPDATE_READAHEAD */
#define HAVE_DLFCN_H 1
/* #undef HAVE_D_MAKE_ROOT */
/* #undef HAVE_D_PRUNE_ALIASES */
/* #undef HAVE_D_REVALIDATE_NAMEIDATA */
/* #undef HAVE_ENCODE_FH_WITH_INODE */
/* #undef HAVE_EVICT_INODE */
/* #undef HAVE_FALLOC_FL_ZERO_RANGE */
/* #undef HAVE_FAULT_IN_IOV_ITER_READABLE */
/* #undef HAVE_FILEMAP_RANGE_HAS_PAGE */
/* #undef HAVE_FILE_AIO_FSYNC */
/* #undef HAVE_FILE_DENTRY */
/* #undef HAVE_FILE_FADVISE */
/* #undef HAVE_FILE_INODE */
/* #undef HAVE_FLUSH_DCACHE_PAGE_GPL_ONLY */
/* #undef HAVE_FOLLOW_LINK_COOKIE */
/* #undef HAVE_FOLLOW_LINK_NAMEIDATA */
#define HAVE_FORMAT_OVERFLOW 1
/* #undef HAVE_FSYNC_BDEV */
/* #undef HAVE_FSYNC_RANGE */
/* #undef HAVE_FSYNC_WITHOUT_DENTRY */
/* #undef HAVE_GENERIC_FADVISE */
/* #undef HAVE_GENERIC_FILLATTR_IDMAP */
/* #undef HAVE_GENERIC_FILLATTR_IDMAP_REQMASK */
/* #undef HAVE_GENERIC_FILLATTR_USERNS */
/* #undef HAVE_GENERIC_IO_ACCT_3ARG */
/* #undef HAVE_GENERIC_IO_ACCT_4ARG */
/* #undef HAVE_GENERIC_READLINK */
/* #undef HAVE_GENERIC_SETXATTR */
/* #undef HAVE_GENERIC_WRITE_CHECKS_KIOCB */
/* #undef HAVE_GETTEXT */
/* #undef HAVE_GET_ACL */
/* #undef HAVE_GET_ACL_RCU */
/* #undef HAVE_GET_INODE_ACL */
/* #undef HAVE_GET_LINK_COOKIE */
/* #undef HAVE_GET_LINK_DELAYED */
/* #undef HAVE_GROUP_INFO_GID */
/* #undef HAVE_HAS_CAPABILITY */
/* #undef HAVE_IATTR_VFSID */
/* #undef HAVE_ICONV */
/* #undef HAVE_IDMAP_IOPS_GETATTR */
/* #undef HAVE_IDMAP_IOPS_SETATTR */
/* #undef HAVE_IDMAP_MNT_API */
/* #undef HAVE_IDMAP_NO_USERNS */
#define HAVE_IMPLICIT_FALLTHROUGH 1
#define HAVE_INFINITE_RECURSION 1
/* #undef HAVE_INODE_GET_ATIME */
/* #undef HAVE_INODE_GET_CTIME */
/* #undef HAVE_INODE_GET_MTIME */
/* #undef HAVE_INODE_LOCK_SHARED */
/* #undef HAVE_INODE_OWNER_OR_CAPABLE */
/* #undef HAVE_INODE_OWNER_OR_CAPABLE_IDMAP */
/* #undef HAVE_INODE_OWNER_OR_CAPABLE_USERNS */
/* #undef HAVE_INODE_SET_ATIME_TO_TS */
/* #undef HAVE_INODE_SET_CTIME_TO_TS */
/* #undef HAVE_INODE_SET_FLAGS */
/* #undef HAVE_INODE_SET_IVERSION */
/* #undef HAVE_INODE_SET_MTIME_TO_TS */
/* #undef HAVE_INODE_TIMESPEC64_TIMES */
/* #undef HAVE_INODE_TIMESTAMP_TRUNCATE */
#define HAVE_INTTYPES_H 1
/* #undef HAVE_IN_COMPAT_SYSCALL */
/* #undef HAVE_IOPS_CREATE_IDMAP */
/* #undef HAVE_IOPS_CREATE_USERNS */
/* #undef HAVE_IOPS_MKDIR_IDMAP */
/* #undef HAVE_IOPS_MKDIR_USERNS */
/* #undef HAVE_IOPS_MKNOD_IDMAP */
/* #undef HAVE_IOPS_MKNOD_USERNS */
/* #undef HAVE_IOPS_PERMISSION_IDMAP */
/* #undef HAVE_IOPS_PERMISSION_USERNS */
/* #undef HAVE_IOPS_RENAME_IDMAP */
/* #undef HAVE_IOPS_RENAME_USERNS */
/* #undef HAVE_IOPS_SETATTR */
/* #undef HAVE_IOPS_SYMLINK_IDMAP */
/* #undef HAVE_IOPS_SYMLINK_USERNS */
/* #undef HAVE_IOV_ITER_ADVANCE */
/* #undef HAVE_IOV_ITER_COUNT */
/* #undef HAVE_IOV_ITER_FAULT_IN_READABLE */
/* #undef HAVE_IOV_ITER_REVERT */
/* #undef HAVE_IOV_ITER_TYPE */
/* #undef HAVE_IOV_ITER_TYPES */
/* #undef HAVE_IO_SCHEDULE_TIMEOUT */
#define HAVE_ISSETUGID 1
/* #undef HAVE_ITER_IOV */
/* #undef HAVE_KERNEL_FPU */
/* #undef HAVE_KERNEL_FPU_API_HEADER */
/* #undef HAVE_KERNEL_FPU_INTERNAL */
/* #undef HAVE_KERNEL_FPU_INTERNAL_HEADER */
/* #undef HAVE_KERNEL_GET_ACL_HANDLE_CACHE */
#define HAVE_KERNEL_INFINITE_RECURSION 1
/* #undef HAVE_KERNEL_NEON */
/* #undef HAVE_KERNEL_OBJTOOL */
/* #undef HAVE_KERNEL_OBJTOOL_HEADER */
/* #undef HAVE_KERNEL_READ_PPOS */
/* #undef HAVE_KERNEL_STRLCPY */
/* #undef HAVE_KERNEL_STRSCPY */
/* #undef HAVE_KERNEL_TIMER_FUNCTION_TIMER_LIST */
/* #undef HAVE_KERNEL_TIMER_LIST_FLAGS */
/* #undef HAVE_KERNEL_TIMER_SETUP */
/* #undef HAVE_KERNEL_WRITE_PPOS */
/* #undef HAVE_KMEM_CACHE_CREATE_USERCOPY */
/* #undef HAVE_KSTRTOUL */
/* #undef HAVE_KTIME_GET_COARSE_REAL_TS64 */
/* #undef HAVE_KTIME_GET_RAW_TS64 */
/* #undef HAVE_KVMALLOC */
/* #undef HAVE_LIBAIO */
#define HAVE_LIBBLKID 1
#define HAVE_LIBCRYPTO 1
#define HAVE_LIBTIRPC 1
/* #undef HAVE_LIBUDEV */
#define HAVE_LIBUUID 1
/* #undef HAVE_LINUX_BLK_CGROUP_HEADER */
/* #undef HAVE_LSEEK_EXECUTE */
/* #undef HAVE_MAKEDEV_IN_MKDEV */
#define HAVE_MAKEDEV_IN_SYSMACROS 1
/* #undef HAVE_MAKE_REQUEST_FN_RET_QC */
/* #undef HAVE_MAKE_REQUEST_FN_RET_VOID */
/* #undef HAVE_MKDIR_UMODE_T */
#define HAVE_MLOCKALL 1
/* #undef HAVE_MODE_LOOKUP_BDEV */
#define HAVE_MOVBE 1
/* #undef HAVE_NEW_SYNC_READ */
/* #undef HAVE_PAGEMAP_FOLIO_WAIT_BIT */
/* #undef HAVE_PART_TO_DEV */
/* #undef HAVE_PATH_IOPS_GETATTR */
#define HAVE_PCLMULQDQ 1
/* #undef HAVE_PERCPU_COUNTER_ADD_BATCH */
/* #undef HAVE_PERCPU_COUNTER_INIT_WITH_GFP */
/* #undef HAVE_POSIX_ACL_CHMOD */
/* #undef HAVE_POSIX_ACL_FROM_XATTR_USERNS */
/* #undef HAVE_POSIX_ACL_RELEASE */
/* #undef HAVE_POSIX_ACL_RELEASE_GPL_ONLY */
/* #undef HAVE_POSIX_ACL_VALID_WITH_NS */
/* #undef HAVE_PROC_OPS_STRUCT */
/* #undef HAVE_PUT_LINK_COOKIE */
/* #undef HAVE_PUT_LINK_DELAYED */
/* #undef HAVE_PUT_LINK_NAMEIDATA */
/* #undef HAVE_PYTHON */
/* #undef HAVE_QAT */
/* #undef HAVE_RECLAIM_STATE_RECLAIMED */
/* #undef HAVE_REGISTER_SHRINKER_VARARG */
/* #undef HAVE_REGISTER_SYSCTL_TABLE */
/* #undef HAVE_RENAME2 */
/* #undef HAVE_RENAME2_OPERATIONS_WRAPPER */
/* #undef HAVE_RENAME_WANTS_FLAGS */
/* #undef HAVE_REQ_DISCARD */
/* #undef HAVE_REQ_FLUSH */
/* #undef HAVE_REQ_OP_DISCARD */
/* #undef HAVE_REQ_OP_FLUSH */
/* #undef HAVE_REQ_OP_SECURE_ERASE */
/* #undef HAVE_REQ_PREFLUSH */
/* #undef HAVE_REVALIDATE_DISK */
/* #undef HAVE_REVALIDATE_DISK_SIZE */
/* #undef HAVE_RWSEM_ACTIVITY */
/* #undef HAVE_RWSEM_ATOMIC_LONG_COUNT */
/* #undef HAVE_SCHED_SIGNAL_HEADER */
/* #undef HAVE_SECURITY_PAM_MODULES_H */
/* #undef HAVE_SETATTR_PREPARE_IDMAP */
/* #undef HAVE_SETATTR_PREPARE_NO_USERNS */
/* #undef HAVE_SETATTR_PREPARE_USERNS */
/* #undef HAVE_SET_ACL */
/* #undef HAVE_SET_ACL_IDMAP_DENTRY */
/* #undef HAVE_SET_ACL_USERNS */
/* #undef HAVE_SET_ACL_USERNS_DENTRY_ARG2 */
/* #undef HAVE_SET_CACHED_ACL_USABLE */
/* #undef HAVE_SET_SPECIAL_STATE */
/* #undef HAVE_SHRINKER_REGISTER */
/* #undef HAVE_SHRINK_CONTROL_STRUCT */
/* #undef HAVE_SIGINFO */
/* #undef HAVE_SIGNAL_STOP */
/* #undef HAVE_SINGLE_SHRINKER_CALLBACK */
/* #undef HAVE_SPLIT_SHRINKER_CALLBACK */
/* #undef HAVE_SSE */
/* #undef HAVE_SSE2 */
/* #undef HAVE_SSE3 */
/* #undef HAVE_SSE4_1 */
/* #undef HAVE_SSE4_2 */
/* #undef HAVE_SSSE3 */
/* #undef HAVE_STACK_FRAME_NON_STANDARD */
/* #undef HAVE_STANDALONE_LINUX_STDARG */
#define HAVE_STDINT_H 1
#define HAVE_STDIO_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRINGS_H 1
#define HAVE_STRING_H 1
#define HAVE_STRLCAT 1
#define HAVE_STRLCPY 1
/* #undef HAVE_SUBMIT_BIO_IN_BLOCK_DEVICE_OPERATIONS */
/* #undef HAVE_SUPER_BLOCK_S_SHRINK */
/* #undef HAVE_SUPER_BLOCK_S_SHRINK_PTR */
/* #undef HAVE_SUPER_SETUP_BDI_NAME */
/* #undef HAVE_SUPER_USER_NS */
/* #undef HAVE_SYNC_BLOCKDEV */
/* #undef HAVE_SYSFS_DEFAULT_GROUPS */
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TYPES_H 1
/* #undef HAVE_TMPFILE */
/* #undef HAVE_TMPFILE_DENTRY */
/* #undef HAVE_TMPFILE_IDMAP */
/* #undef HAVE_TMPFILE_USERNS */
/* #undef HAVE_TOTALHIGH_PAGES */
/* #undef HAVE_TOTALRAM_PAGES_FUNC */
/* #undef HAVE_UDEV_DEVICE_GET_IS_INITIALIZED */
/* #undef HAVE_UNDERSCORE_KERNEL_FPU */
#define HAVE_UNISTD_H 1
/* #undef HAVE_USERNS_IOPS_GETATTR */
/* #undef HAVE_USERNS_IOPS_SETATTR */
/* #undef HAVE_USER_NS_COMMON_INUM */
/* #undef HAVE_VFSMOUNT_IOPS_GETATTR */
/* #undef HAVE_VFS_CLONE_FILE_RANGE */
/* #undef HAVE_VFS_COPY_FILE_RANGE */
/* #undef HAVE_VFS_DEDUPE_FILE_RANGE */
/* #undef HAVE_VFS_DIRECT_IO_IOVEC */
/* #undef HAVE_VFS_DIRECT_IO_ITER */
/* #undef HAVE_VFS_DIRECT_IO_ITER_OFFSET */
/* #undef HAVE_VFS_DIRECT_IO_ITER_RW_OFFSET */
/* #undef HAVE_VFS_FILEMAP_DIRTY_FOLIO */
/* #undef HAVE_VFS_FILE_OPERATIONS_EXTEND */
/* #undef HAVE_VFS_GENERIC_COPY_FILE_RANGE */
/* #undef HAVE_VFS_IOV_ITER */
/* #undef HAVE_VFS_ITERATE */
/* #undef HAVE_VFS_ITERATE_SHARED */
/* #undef HAVE_VFS_READDIR */
/* #undef HAVE_VFS_READPAGES */
/* #undef HAVE_VFS_READ_FOLIO */
/* #undef HAVE_VFS_REMAP_FILE_RANGE */
/* #undef HAVE_VFS_RW_ITERATE */
/* #undef HAVE_VFS_SET_PAGE_DIRTY_NOBUFFERS */
/* #undef HAVE_VMALLOC_PAGE_KERNEL */
/* #undef HAVE_WAIT_ON_BIT_ACTION */
/* #undef HAVE_WAIT_QUEUE_ENTRY_T */
/* #undef HAVE_WAIT_QUEUE_HEAD_ENTRY */
/* #undef HAVE_WRITEPAGE_T_FOLIO */
/* #undef HAVE_XATTR_GET_DENTRY */
/* #undef HAVE_XATTR_GET_DENTRY_INODE */
/* #undef HAVE_XATTR_GET_DENTRY_INODE_FLAGS */
/* #undef HAVE_XATTR_GET_HANDLER */
/* #undef HAVE_XATTR_HANDLER_NAME */
/* #undef HAVE_XATTR_LIST_DENTRY */
/* #undef HAVE_XATTR_LIST_HANDLER */
/* #undef HAVE_XATTR_LIST_SIMPLE */
/* #undef HAVE_XATTR_SET_DENTRY */
/* #undef HAVE_XATTR_SET_DENTRY_INODE */
/* #undef HAVE_XATTR_SET_HANDLER */
/* #undef HAVE_XATTR_SET_IDMAP */
/* #undef HAVE_XATTR_SET_USERNS */
#define HAVE_XSAVE 1
#define HAVE_XSAVEOPT 1
#define HAVE_XSAVES 1
/* #undef HAVE_ZERO_PAGE_GPL_ONLY */
#define HAVE_ZLIB 1
/* #undef HAVE___POSIX_ACL_CHMOD */
/* #undef KERNEL_EXPORTS_X86_FPU */
#define LIBFETCH_DYNAMIC 0
#define LIBFETCH_IS_FETCH 0
#define LIBFETCH_IS_LIBCURL 0
#define LIBFETCH_SONAME ""
#define LT_OBJDIR ".libs/"
/* #undef MAKE_REQUEST_FN_RET */
#define PACKAGE "zfs"
#define PACKAGE_BUGREPORT ""
#define PACKAGE_NAME "zfs"
#define PACKAGE_STRING "zfs 2.2.3"
#define PACKAGE_TARNAME "zfs"
#define PACKAGE_URL ""
#define PACKAGE_VERSION "2.2.3"
/* #undef SHRINK_CONTROL_HAS_NID */
/* #undef SPL_KTHREAD_COMPLETE_AND_EXIT */
#define SPL_META_ALIAS ZFS_META_ALIAS
#define SPL_META_RELEASE ZFS_META_RELEASE
#define SPL_META_VERSION ZFS_META_VERSION
/* #undef SPL_PDE_DATA */
#define STDC_HEADERS 1
/* #undef SYSTEM_FREEBSD */
#define SYSTEM_LINUX 1
#define VERSION "2.2.3"
/* #undef ZFS_DEBUG */
/* #undef ZFS_DEVICE_MINOR */
/* #undef ZFS_ENUM_NODE_STAT_ITEM_NR_FILE_PAGES */
/* #undef ZFS_ENUM_NODE_STAT_ITEM_NR_INACTIVE_ANON */
/* #undef ZFS_ENUM_NODE_STAT_ITEM_NR_INACTIVE_FILE */
/* #undef ZFS_ENUM_ZONE_STAT_ITEM_NR_FILE_PAGES */
/* #undef ZFS_ENUM_ZONE_STAT_ITEM_NR_INACTIVE_ANON */
/* #undef ZFS_ENUM_ZONE_STAT_ITEM_NR_INACTIVE_FILE */
/* #undef ZFS_GENHD_FL_EXT_DEVT */
/* #undef ZFS_GENHD_FL_NO_PART */
/* #undef ZFS_GLOBAL_NODE_PAGE_STATE */
/* #undef ZFS_GLOBAL_ZONE_PAGE_STATE */
/* #undef ZFS_IS_GPL_COMPATIBLE */
#define ZFS_META_ALIAS "zfs-2.2.3-1"
#define ZFS_META_AUTHOR "OpenZFS"
/* #undef ZFS_META_DATA */
#define ZFS_META_KVER_MAX "6.7"
#define ZFS_META_KVER_MIN "3.10"
#define ZFS_META_LICENSE "CDDL"
/* #undef ZFS_META_LT_AGE */
/* #undef ZFS_META_LT_CURRENT */
/* #undef ZFS_META_LT_REVISION */
#define ZFS_META_NAME "zfs"
#define ZFS_META_RELEASE "1"
#define ZFS_META_VERSION "2.2.3"
/* #undef ZFS_PERCPU_REF_COUNT_IN_DATA */

#define ZFSEXECDIR "/libexec/zfs"
#define RUNSTATEDIR "/run"
#define SBINDIR "/bin"
#define SYSCONFDIR "/etc"
#define PKGDATADIR "/share/zfs"
#define TEXT_DOMAIN "zfs-linux-user"
