#define BC_ENABLED 1
#define DC_ENABLED 0

#define BC_ENABLE_EXTRA_MATH 1
#define BC_ENABLE_HISTORY 1
#define BC_ENABLE_NLS 0
#define BC_ENABLE_PROMPT 1
#define BC_ENABLE_SIGNALS 1
#define BC_NUM_KARATSUBA_LEN 64
