#ifndef W_CONFIG_H_WAF
#define W_CONFIG_H_WAF

#define DEFAULT_DVD_DEVICE "/dev/sr0"
#define DEFAULT_CDROM_DEVICE "/dev/sr0"
#define HAVE_CPLAYER 1
#define HAVE_LIBMPV_SHARED 0
#define HAVE_LIBMPV_STATIC 0
#define HAVE_STATIC_BUILD 0
#define HAVE_BUILD_DATE 1
#define HAVE_OPTIMIZE 1
#define HAVE_DEBUG_BUILD 1
#define HAVE_MANPAGE_BUILD 0
#define HAVE_HTML_BUILD 0
#define HAVE_PDF_BUILD 0
#define HAVE_LIBDL 1
#define HAVE_DLOPEN 0
#define HAVE_VF_DLOPEN_FILTERS 0
#define HAVE_ZSH_COMP 0
#define HAVE_ASM 1
#define HAVE_TEST 0
#define HAVE_CLANG_DATABASE 0
#define HAVE_NOEXECSTACK 0
#define HAVE_LIBM 1
#define HAVE_MINGW 0
#define HAVE_POSIX 1
#define HAVE_FNMATCH 1
#define HAVE_POSIX_OR_MINGW 1
#define HAVE_WIN32 0
#define HAVE_WIN32_INTERNAL_PTHREADS 0
#define HAVE_PTHREADS 1
#define HAVE_GNUC 1
#define HAVE_STDATOMIC 1
#define HAVE_ATOMIC_BUILTINS 0
#define HAVE_SYNC_BUILTINS 0
#define HAVE_ATOMICS 1
#define HAVE_C11_TLS 1
#define HAVE_GCC_TLS 1
#define HAVE_LIBRT 1
#define HAVE_ICONV 1
#define HAVE_DOS_PATHS 0
#define HAVE_TERMIOS_H 1
#define HAVE_SYS_TERMIOS_H 0
#define HAVE_TERMIOS 1
#define HAVE_SHM 1
#define HAVE_NANOSLEEP 1
#define HAVE_POSIX_SPAWN 1
#define HAVE_SUBPROCESS 1
#define HAVE_GLOB 1
#define HAVE_GLOB_WIN32_REPLACEMENT 0
#define HAVE_FCHMOD 1
#define HAVE_VT_H 1
#define HAVE_GBM_H 0
#define HAVE_GLIBC_THREAD_NAME 0
#define HAVE_OSX_THREAD_NAME 0
#define HAVE_BSD_THREAD_NAME 0
#define HAVE_NETBSD_THREAD_NAME 0
#define HAVE_BSD_FSTATFS 0
#define HAVE_LINUX_FSTATFS 1
#define HAVE_LIBSMBCLIENT 0
#define HAVE_LUA 1
#define HAVE_LIBASS 1
#define HAVE_LIBASS_OSD 1
#define HAVE_DUMMY_OSD 0
#define HAVE_ZLIB 1
#define HAVE_ENCODING 0
#define HAVE_LIBBLURAY 0
#define HAVE_DVDREAD 0
#define HAVE_DVDNAV 0
#define HAVE_CDDA 0
#define HAVE_ENCA 0
#define HAVE_LIBGUESS 0
#define HAVE_UCHARDET 0
#define HAVE_RUBBERBAND 0
#define HAVE_LCMS2 0
#define HAVE_VAPOURSYNTH 0
#define HAVE_VAPOURSYNTH_LAZY 0
#define HAVE_VAPOURSYNTH_CORE 0
#define HAVE_LIBARCHIVE 0
#define HAVE_SDL2 0
#define HAVE_SDL1 0
#define HAVE_OSS_AUDIO_4FRONT 0
#define HAVE_OSS_AUDIO_NATIVE 1
#define HAVE_OSS_AUDIO_SUNAUDIO 0
#define HAVE_OSS_AUDIO 0
#define HAVE_RSOUND 0
#define HAVE_SNDIO 0
#define HAVE_PULSE 0
#define HAVE_JACK 0
#define HAVE_OPENAL 0
#define HAVE_OPENSLES 0
#define HAVE_ALSA 1
#define HAVE_COREAUDIO 0
#define HAVE_AUDIOUNIT 0
#define HAVE_WASAPI 0
#define HAVE_COCOA 0
#define HAVE_DRM 1
#define HAVE_GBM 0
#define HAVE_WAYLAND 0
#define HAVE_X11 0
#define HAVE_XSS 0
#define HAVE_XEXT 0
#define HAVE_XV 0
#define HAVE_XINERAMA 0
#define HAVE_XRANDR 0
#define HAVE_GL_COCOA 0
#define HAVE_GL_X11 0
#define HAVE_EGL_X11 0
#define HAVE_EGL_DRM 0
#define HAVE_GL_WAYLAND 0
#define HAVE_GL_WIN32 0
#define HAVE_GL_DXINTEROP 0
#define HAVE_EGL_ANGLE 0
#define HAVE_VDPAU 0
#define HAVE_VDPAU_GL_X11 0
#define HAVE_VAAPI 0
#define HAVE_VAAPI_X11 0
#define HAVE_VAAPI_WAYLAND 0
#define HAVE_VAAPI_DRM 0
#define HAVE_VAAPI_GLX 0
#define HAVE_VAAPI_X_EGL 0
#define HAVE_VAAPI_EGL 0
#define HAVE_CACA 0
#define HAVE_JPEG 0
#define HAVE_DIRECT3D 0
#define HAVE_ANDROID 0
#define HAVE_RPI 0
#define HAVE_STANDARD_GL 0
#define HAVE_ANDROID_GL 0
#define HAVE_IOS_GL 0
#define HAVE_ANY_GL 0
#define HAVE_PLAIN_GL 0
#define HAVE_MALI_FBDEV 0
#define HAVE_GL 0
#define HAVE_EGL_HELPERS 0
#define HAVE_LIBAV 1
#define HAVE_LIBSWRESAMPLE 1
#define HAVE_LIBAVRESAMPLE 0
#define HAVE_RESAMPLER 1
#define HAVE_LIBAVFILTER 1
#define HAVE_LIBAVDEVICE 1
#define HAVE_AVCODEC_CHROMA_POS_API 1
#define HAVE_AVFRAME_METADATA 1
#define HAVE_AVFRAME_SKIP_SAMPLES 1
#define HAVE_AV_PIX_FMT_MMAL 1
#define HAVE_AV_VERSION_INFO 1
#define HAVE_AV_NEW_PIXDESC 1
#define HAVE_AV_AVPACKET_INT64_DURATION 1
#define HAVE_AV_SUBTITLE_NOPICT 1
#define HAVE_AVCODEC_PROFILE_NAME 1
#define HAVE_AVCODEC_NEW_CODEC_API 1
#define HAVE_AVCODEC_HAS_CODECPAR 1
#define HAVE_AVUTIL_HAS_HWCONTEXT 1
#define HAVE_AVUTIL_HDR 1
#define HAVE_AVUTIL_MASTERING_METADATA 1
#define HAVE_VAAPI_HWACCEL 0
#define HAVE_VIDEOTOOLBOX_VIDEOTOOLBOX_H 0
#define HAVE_VIDEO_TOOLBOX_VIDEO_TOOLBOX_H 0
#define HAVE_VIDEOTOOLBOX_HWACCEL 0
#define HAVE_VIDEOTOOLBOX_GL 0
#define HAVE_VDPAU_HWACCEL 0
#define HAVE_D3D_HWACCEL 0
#define HAVE_CUDA_HWACCEL 0
#define HAVE_SSE4_INTRINSICS 0
#define HAVE_TV 0
#define HAVE_SYS_VIDEOIO_H 0
#define HAVE_VIDEODEV 1
#define HAVE_TV_V4L2 0
#define HAVE_LIBV4L2 0
#define HAVE_AUDIO_INPUT 0
#define HAVE_DVBIN 0
#define HAVE_WIN32_EXECUTABLE 0
#define HAVE_APPLE_REMOTE 0
#define HAVE_SYS_SOUNDCARD_H (HAVE_OSS_AUDIO_NATIVE || HAVE_OSS_AUDIO_4FRONT)
#define HAVE_SOUNDCARD_H HAVE_OSS_AUDIO_SUNAUDIO
#define CONFIGURATION "./waf configure --disable-libass --disable-gl"
#define MPV_CONFDIR "/etc/mpv"
#define FULLCONFIG "asm atomics audio-input av-pix-fmt-mmal av-version-info avcodec-chroma-pos-api avframe-metadata avframe-skip-samples build-date c11-tls cplayer debug-build dlopen dummy-osd dvbin encoding fchmod glob iconv libav libavdevice libavfilter libdl libm librt libswresample linux-fstatfs nanosleep optimize oss-audio oss-audio-native posix posix-or-mingw posix-spawn pthreads resampler shm stdatomic subprocess termios tv tv-v4l2 videodev vt.h zlib"

#endif /* W_CONFIG_H_WAF */
