/^#define/ {
	cfg[$2] = $3
}

function printvar(var) {
	print "#define AV_" var " " cfg[var]
}

END {
	print "/* generated by avconfig.awk */"
	print "#ifndef AVUTIL_AVCONFIG_H"
	print "#define AVUTIL_AVCONFIG_H"
	printvar("HAVE_BIGENDIAN")
	printvar("HAVE_FAST_UNALIGNED")
	print "#endif /* AVUTIL_AVCONFIG_H */"
}
