#define _FIDO_MAJOR 1
#define _FIDO_MINOR 5
#define _FIDO_PATCH 0
#ifdef HAVE__THREAD_LOCAL
# define TLS _Thread_local
#endif
#define HAVE_ENDIAN_H
#define HAVE_ERR_H
#define HAVE_UNISTD_H
#define HAVE_SIGNAL_H
#define HAVE_SYS_RANDOM_H
#define HAVE_STRLCPY
#define HAVE_STRLCAT
#define HAVE_RECALLOCARRAY
#define HAVE_GETPAGESIZE
#define HAVE_SYSCONF
/* #undef HAVE_MEMSET_S */
#define HAVE_EXPLICIT_BZERO
#define HAVE_TIMINGSAFE_BCMP
#define HAVE_READPASSPHRASE
#define HAVE_GETLINE
#define HAVE_GETOPT
/* #undef HAVE_ARC4RANDOM_BUF */
#define HAVE_GETRANDOM
#define HAVE_DEV_URANDOM
