#define TLS _Thread_local
#define HAS_DEV_URANDOM
#define HAVE_ENDIAN_H
#define HAVE_ERR_H
#define HAVE_UNISTD_H
#define HAVE_SIGNAL_H
#define HAVE_STRLCPY
#define HAVE_STRLCAT
#define HAVE_RECALLOCARRAY
#define HAVE_GETPAGESIZE
#define HAVE_SYSCONF
#define HAVE_EXPLICIT_BZERO
#define HAVE_TIMINGSAFE_BCMP
#define HAVE_READPASSPHRASE
#define HAVE_GETLINE
#define HAVE_GETOPT
