#define _FIDO_MAJOR 1
#define _FIDO_MINOR 7
#define _FIDO_PATCH 0
#ifdef HAVE__THREAD_LOCAL
# define TLS _Thread_local
#endif
/* #undef HAVE_ARC4RANDOM_BUF */
#define HAVE_CBOR_H
#define HAVE_CLOCK_GETTIME
#define HAVE_DEV_URANDOM
#define HAVE_ENDIAN_H
#define HAVE_ERR_H
#define HAVE_EXPLICIT_BZERO
#define HAVE_FREEZERO
#define HAVE_GETLINE
#define HAVE_GETOPT
#define HAVE_GETPAGESIZE
#define HAVE_GETRANDOM
/* #undef HAVE_MEMSET_S */
#define HAVE_POSIX_IOCTL
#define HAVE_READPASSPHRASE
#define HAVE_RECALLOCARRAY
#define HAVE_SIGACTION
#define HAVE_SIGNAL_H
#define HAVE_STRLCAT
#define HAVE_STRLCPY
#define HAVE_SYSCONF
#define HAVE_SYS_RANDOM_H
/* #undef HAVE_TIMESPECSUB */
#define HAVE_TIMINGSAFE_BCMP
#define HAVE_UNISTD_H
/* #undef HAVE_WEBAUTHN_H */
