#define ZSTD_NO_UNUSED_FUNCTIONS
#define ZSTD_MULTITHREAD
#define XXH_NAMESPACE ZSTD_
#define ZSTD_NOBENCH
#define ZSTD_NODICT
#define ZSTD_NOTRACE
#define ZSTD_DISABLE_DEPRECATE_WARNINGS
#define ZDICT_DISABLE_DEPRECATE_WARNINGS
